import type { CentralBankBalanceConfig } from "../contracts/balance-config";

export const freeModeCentralBankConfig: CentralBankBalanceConfig = {
  id: "central_bank",
  buildingTypeId: "central_bank",
  countOnMap: 2,
  zone: "downtown",
  category: ["ultra_rare", "finance", "reserve", "market_stability"],
  cleanCashPerMinute: 160,
  dirtyCashPerMinute: 0,
  influencePerMinute: 0.35,
  populationPerMinute: 0,
  heatPerMinute: 0.1,
  noIntelPower: true,
  noDirtyCash: true,
  noPopulationProduction: true,
  noLaundering: true,
  reserveTiers: [
    {
      minOwned: 1,
      maxOwned: 1,
      cleanCashProtectionPct: 12,
      interestIntervalMinutes: 10,
      interestPct: 2.5,
      maxInterestCleanCash: 2500,
      incomeMultiplier: 1,
      influenceMultiplier: 1,
      heatMultiplier: 1,
      fineReductionPct: 10,
      marketFeeReductionPct: 5,
      financialInspectionPenaltyReductionPct: 8,
      economicCrisisImpactReductionPct: 12
    },
    {
      minOwned: 2,
      maxOwned: 2,
      cleanCashProtectionPct: 22,
      interestIntervalMinutes: 10,
      interestPct: 4,
      maxInterestCleanCash: 4000,
      incomeMultiplier: 1.18,
      influenceMultiplier: 1.15,
      heatMultiplier: 1.12,
      fineReductionPct: 18,
      marketFeeReductionPct: 8,
      financialInspectionPenaltyReductionPct: 14,
      economicCrisisImpactReductionPct: 20
    }
  ],
  liquidityInjection: {
    actionId: "liquidity_injection",
    cooldownMinutes: 20,
    costInfluence: 20,
    heatGain: 4,
    baseRewardCleanCash: 2500,
    rewardPerCleanEconomyBuilding: 90,
    maxRewardCleanCash: 8000,
    shoppingMallRewardBonusPct: 8,
    riskPct: 6,
    riskDurationMinutes: 8,
    cleanEconomyBuildingTypeIds: [
      "restaurant",
      "convenience_store",
      "shopping_mall",
      "garage",
      "car_dealer",
      "warehouse",
      "fitness_club",
      "school",
      "clinic",
      "recycling_center",
      "power_station",
      "city_hall",
      "stock_exchange",
      "airport",
      "port",
      "vip_lounge"
    ]
  },
  frozenAccounts: {
    actionId: "frozen_accounts",
    cooldownMinutes: 24,
    durationMinutes: 8,
    costCleanCash: 2000,
    heatGain: 5,
    cleanCashProtectionBonusPct: 25,
    dirtyCashProtectionPct: 8,
    fineReductionPct: 20,
    financialEventLossReductionPct: 25,
    marketFeePenaltyPct: 5,
    riskPct: 8
  },
  currencyIntervention: {
    actionId: "currency_intervention",
    cooldownMinutes: 28,
    durationMinutes: 8,
    costCleanCash: 3000,
    costInfluence: 25,
    heatGain: 7,
    targetCategories: ["materials", "weapons", "defenseItems", "rareComponents", "drugsAndBoosts"],
    volatilityReductionPct: 30,
    priceMoveCapPct: 6,
    holderMarketFeeReductionPct: 6,
    stockExchangeEffectReductionPct: 25,
    stockExchangeSynergyEffectBonusPct: 10,
    riskPct: 12
  },
  financialOversight: {
    intervalMinutes: 8,
    passiveRiskPct: 2,
    heatThreshold: 150,
    heatRiskPct: 8,
    stockExchangeRiskPct: 5,
    cityHallRiskReductionPct: 4,
    interestDisabledMinutes: 8,
    liquidityBlockedMinutes: 8,
    regulatoryFineCleanCash: 3500,
    feeReductionDisabledMinutes: 8
  },
  synergies: {
    stockExchangeSpeculativeRiskReductionPct: 5,
    cityHallCorruptionPenaltyReductionPct: 8,
    cityHallInfluenceActionCostReductionPct: 3,
    shoppingMallMarketFeeReductionPct: 3,
    shoppingMallCleanIncomeBonusPct: 4
  }
};
