-- Empire Streets production runtime persistence schema.
-- Compatible with standard Postgres and Supabase-hosted Postgres.

CREATE TABLE IF NOT EXISTS empire_server_instances (
  id text PRIMARY KEY,
  server_instance_id text NOT NULL UNIQUE,
  schema_version integer NOT NULL DEFAULT 1,
  mode text NOT NULL,
  status text NOT NULL,
  lock_version bigint NOT NULL DEFAULT 0,
  tick_lock_owner text,
  tick_lock_expires_at timestamptz,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS empire_server_instances_status_idx
  ON empire_server_instances (status, updated_at DESC);

CREATE INDEX IF NOT EXISTS empire_server_instances_tick_lock_idx
  ON empire_server_instances (server_instance_id, tick_lock_expires_at);

CREATE TABLE IF NOT EXISTS empire_command_log (
  id text PRIMARY KEY,
  server_instance_id text NOT NULL REFERENCES empire_server_instances (server_instance_id) ON DELETE CASCADE,
  schema_version integer NOT NULL DEFAULT 1,
  sequence bigint GENERATED BY DEFAULT AS IDENTITY,
  command_id text NOT NULL,
  actor_id text NOT NULL,
  correlation_id text,
  tick_at_receive integer NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (server_instance_id, command_id),
  UNIQUE (server_instance_id, sequence)
);

CREATE INDEX IF NOT EXISTS empire_command_log_instance_created_idx
  ON empire_command_log (server_instance_id, created_at);

CREATE INDEX IF NOT EXISTS empire_command_log_instance_sequence_idx
  ON empire_command_log (server_instance_id, sequence);

CREATE INDEX IF NOT EXISTS empire_command_log_actor_idx
  ON empire_command_log (server_instance_id, actor_id, created_at);

CREATE TABLE IF NOT EXISTS empire_event_log (
  id text PRIMARY KEY,
  server_instance_id text NOT NULL REFERENCES empire_server_instances (server_instance_id) ON DELETE CASCADE,
  schema_version integer NOT NULL DEFAULT 1,
  sequence bigint GENERATED BY DEFAULT AS IDENTITY,
  caused_by_command_id text,
  tick_at_emit integer NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (server_instance_id, sequence)
);

CREATE INDEX IF NOT EXISTS empire_event_log_instance_created_idx
  ON empire_event_log (server_instance_id, created_at);

CREATE INDEX IF NOT EXISTS empire_event_log_instance_sequence_idx
  ON empire_event_log (server_instance_id, sequence);

CREATE INDEX IF NOT EXISTS empire_event_log_command_idx
  ON empire_event_log (server_instance_id, caused_by_command_id);

CREATE TABLE IF NOT EXISTS empire_diagnostic_log (
  id text PRIMARY KEY,
  server_instance_id text NOT NULL REFERENCES empire_server_instances (server_instance_id) ON DELETE CASCADE,
  schema_version integer NOT NULL DEFAULT 1,
  sequence bigint GENERATED BY DEFAULT AS IDENTITY,
  level text NOT NULL,
  category text NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (server_instance_id, sequence)
);

CREATE INDEX IF NOT EXISTS empire_diagnostic_log_instance_created_idx
  ON empire_diagnostic_log (server_instance_id, created_at);

CREATE INDEX IF NOT EXISTS empire_diagnostic_log_level_idx
  ON empire_diagnostic_log (server_instance_id, level, created_at);

CREATE TABLE IF NOT EXISTS empire_snapshots (
  id text PRIMARY KEY,
  server_instance_id text NOT NULL REFERENCES empire_server_instances (server_instance_id) ON DELETE CASCADE,
  schema_version integer NOT NULL DEFAULT 1,
  snapshot_id text NOT NULL,
  root_version bigint NOT NULL,
  tick integer NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (server_instance_id, snapshot_id),
  UNIQUE (server_instance_id, root_version)
);

CREATE INDEX IF NOT EXISTS empire_snapshots_instance_created_idx
  ON empire_snapshots (server_instance_id, created_at DESC);

CREATE INDEX IF NOT EXISTS empire_snapshots_instance_root_version_idx
  ON empire_snapshots (server_instance_id, root_version DESC);

CREATE TABLE IF NOT EXISTS empire_snapshot_latest (
  id text PRIMARY KEY,
  server_instance_id text NOT NULL UNIQUE REFERENCES empire_server_instances (server_instance_id) ON DELETE CASCADE,
  schema_version integer NOT NULL DEFAULT 1,
  snapshot_id text NOT NULL,
  root_version bigint NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS empire_snapshot_latest_root_version_idx
  ON empire_snapshot_latest (server_instance_id, root_version DESC);

CREATE TABLE IF NOT EXISTS empire_player_registrations (
  id text PRIMARY KEY,
  server_instance_id text NOT NULL REFERENCES empire_server_instances (server_instance_id) ON DELETE CASCADE,
  schema_version integer NOT NULL DEFAULT 1,
  player_id text NOT NULL,
  account_id text,
  session_id text,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (server_instance_id, player_id),
  UNIQUE (server_instance_id, session_id)
);

CREATE INDEX IF NOT EXISTS empire_player_registrations_player_idx
  ON empire_player_registrations (player_id, created_at DESC);

CREATE INDEX IF NOT EXISTS empire_player_registrations_account_idx
  ON empire_player_registrations (account_id, created_at DESC);

CREATE TABLE IF NOT EXISTS empire_tick_locks (
  id text PRIMARY KEY,
  server_instance_id text NOT NULL UNIQUE REFERENCES empire_server_instances (server_instance_id) ON DELETE CASCADE,
  schema_version integer NOT NULL DEFAULT 1,
  lock_owner text NOT NULL,
  locked_until timestamptz NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS empire_tick_locks_expiry_idx
  ON empire_tick_locks (server_instance_id, locked_until);
