import type { ResolvedGameModeConfig } from "../../contracts/game-mode-config";
import { freeModeAirportConfig } from "../../public/free-mode-airport-config";
import { freeModeCentralBankConfig } from "../../public/free-mode-central-bank-config";
import { freeModeCityHallConfig } from "../../public/free-mode-city-hall-config";
import { freeModeParliamentConfig } from "../../public/free-mode-parliament-config";
import { freeModePortConfig } from "../../public/free-mode-port-config";
import { freeModeStockExchangeConfig } from "../../public/free-mode-stock-exchange-config";
import { freeModeLobbyClubBuildingActions } from "./free-mode-lobby-club-building-actions";

export const freeModeInstitutionalBuildingActions: NonNullable<ResolvedGameModeConfig["balance"]["buildingActions"]> = {  official_cover: {
    actionId: "official_cover",
    buildingType: "city_hall",
    label: "Úřední krytí",
    description: "Na 8 minut sníží heat gain, police control chance a rumor chance ve všech vlastněných districtech.",
    durationMs: freeModeCityHallConfig.officialCover.durationMinutes * 60 * 1000,
    cooldownMs: freeModeCityHallConfig.officialCover.cooldownMinutes * 60 * 1000,
    inputCost: { cash: freeModeCityHallConfig.officialCover.costCleanCash },
    outputGain: {},
    heatGain: freeModeCityHallConfig.officialCover.heatGain,
    influenceChange: -freeModeCityHallConfig.officialCover.costInfluence,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Úřední krytí je aktivní. Všechny vlastněné districty mají dočasně slabší heat a policejní tlak."
  },
  city_contract: {
    actionId: "city_contract",
    buildingType: "city_hall",
    label: "Městská zakázka",
    description: "Převede politický vliv na clean cash podle počtu legálních budov hráče.",
    durationMs: 0,
    cooldownMs: freeModeCityHallConfig.cityContract.cooldownMinutes * 60 * 1000,
    inputCost: {},
    outputGain: {},
    heatGain: freeModeCityHallConfig.cityContract.heatGain,
    influenceChange: -freeModeCityHallConfig.cityContract.costInfluence,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Městská zakázka připsala clean cash podle legální infrastruktury."
  },
  emergency_decree: {
    actionId: "emergency_decree",
    buildingType: "city_hall",
    label: "Nouzová vyhláška",
    description: "Na 6 minut spustí městský režim: Noční hlídky, Zastavené kontroly nebo Stavební uzávěru.",
    durationMs: freeModeCityHallConfig.emergencyDecree.durationMinutes * 60 * 1000,
    cooldownMs: freeModeCityHallConfig.emergencyDecree.cooldownMinutes * 60 * 1000,
    inputCost: { cash: freeModeCityHallConfig.emergencyDecree.costCleanCash },
    outputGain: {},
    heatGain: freeModeCityHallConfig.emergencyDecree.heatGain,
    influenceChange: -freeModeCityHallConfig.emergencyDecree.costInfluence,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Magistrát vydal nouzovou vyhlášku. Město se na chvíli mění."
  },
  express_import: {
    actionId: "express_import",
    buildingType: "airport",
    label: "Expresní dovoz",
    description: "Po 90 sekundách doručí importní zásilku vybrané kategorie do skladu hráče. Přesah přes storage kapacitu propadne.",
    durationMs: freeModeAirportConfig.expressImport.durationSeconds * 1000,
    cooldownMs: freeModeAirportConfig.expressImport.cooldownMinutes * 60 * 1000,
    inputCost: { cash: freeModeAirportConfig.expressImport.costCleanCash },
    outputGain: {},
    heatGain: freeModeAirportConfig.expressImport.heatGain,
    influenceChange: 0,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Expresní dovoz byl objednán. Zásilka dorazí po krátkém runway okně."
  },
  black_charter: {
    actionId: "black_charter",
    buildingType: "airport",
    label: "Černý charter",
    description: "Na 8 minut otevře speciální Black Market nabídku se slevou a celním rizikem při nákupu.",
    durationMs: freeModeAirportConfig.blackCharter.durationMinutes * 60 * 1000,
    cooldownMs: freeModeAirportConfig.blackCharter.cooldownMinutes * 60 * 1000,
    inputCost: { "dirty-cash": freeModeAirportConfig.blackCharter.costDirtyCash },
    outputGain: {},
    heatGain: freeModeAirportConfig.blackCharter.heatGain,
    influenceChange: 0,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Černý charter otevřel dočasnou Black Market nabídku."
  },
  evacuation_corridor: {
    actionId: "evacuation_corridor",
    buildingType: "airport",
    label: "Evakuační koridor",
    description: "Na 7 minut zlepší únik, sníží ztráty při neúspěchu a zrychlí návratové logistické časy.",
    durationMs: freeModeAirportConfig.evacuationCorridor.durationMinutes * 60 * 1000,
    cooldownMs: freeModeAirportConfig.evacuationCorridor.cooldownMinutes * 60 * 1000,
    inputCost: { cash: freeModeAirportConfig.evacuationCorridor.costCleanCash },
    outputGain: {},
    heatGain: freeModeAirportConfig.evacuationCorridor.heatGain,
    influenceChange: 0,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Evakuační koridor je aktivní. Únik a logistika mají dočasný boost."
  },
  port_container_cut: {
    actionId: "port_container_cut",
    buildingType: "port",
    label: "Container Cut",
    description: "Vybere z kontejnerů užitečné zásoby a dirty cash přes přístavní trasu.",
    durationMs: 0,
    cooldownMs: freeModePortConfig.containerCut.cooldownMinutes * 60 * 1000,
    inputCost: {},
    outputGain: {
      "dirty-cash": freeModePortConfig.containerCut.dirtyCashGain,
      "metal-parts": freeModePortConfig.containerCut.metalPartsGain
    },
    heatGain: freeModePortConfig.containerCut.heatGain,
    influenceChange: freeModePortConfig.containerCut.influenceGain,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Přístav rozebral kontejnerovou trasu a vytáhl dirty cash i metal parts."
  },
  parliament_policy_window: {
    actionId: "parliament_policy_window",
    buildingType: "parliament",
    label: "Policy Window",
    description: "Otevře krátké politické okno pro zisk vlivu a clean cash.",
    durationMs: 0,
    cooldownMs: freeModeParliamentConfig.policyWindow.cooldownMinutes * 60 * 1000,
    inputCost: {},
    outputGain: { cash: freeModeParliamentConfig.policyWindow.cleanCashGain },
    heatGain: freeModeParliamentConfig.policyWindow.heatGain,
    influenceChange: freeModeParliamentConfig.policyWindow.influenceGain,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Parlament otevřel politické okno a přidal vliv i clean cash."
  },
  speculative_buy: {
    actionId: "speculative_buy",
    buildingType: "stock_exchange",
    label: "Spekulativní nákup",
    description: "Investuje clean cash do vybrané market kategorie. Výsledek může být zisk, neutrální pohyb nebo ztráta.",
    durationMs: 0,
    cooldownMs: freeModeStockExchangeConfig.speculativeBuy.cooldownMinutes * 60 * 1000,
    inputCost: { cash: freeModeStockExchangeConfig.speculativeBuy.costCleanCash },
    outputGain: {},
    heatGain: freeModeStockExchangeConfig.speculativeBuy.heatGain,
    influenceChange: 0,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Burza provedla spekulativní nákup a zvýšila financial inspection risk."
  },
  market_pressure: {
    actionId: "market_pressure",
    buildingType: "stock_exchange",
    label: "Tržní tlak",
    description: "Na 10 minut server-wide pumpne nebo dumpne ceny vybrané market kategorie.",
    durationMs: freeModeStockExchangeConfig.marketPressure.durationMinutes * 60 * 1000,
    cooldownMs: freeModeStockExchangeConfig.marketPressure.cooldownMinutes * 60 * 1000,
    inputCost: { cash: freeModeStockExchangeConfig.marketPressure.costCleanCash },
    outputGain: {},
    heatGain: freeModeStockExchangeConfig.marketPressure.heatGain,
    influenceChange: -freeModeStockExchangeConfig.marketPressure.costInfluence,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Downtown burza rozkolísala ceny ve vybrané kategorii."
  },
  insider_window: {
    actionId: "insider_window",
    buildingType: "stock_exchange",
    label: "Insider Window",
    description: "Na 6 minut zlepší trend hints, fee reduction a šanci Spekulativního nákupu.",
    durationMs: freeModeStockExchangeConfig.insiderWindow.durationMinutes * 60 * 1000,
    cooldownMs: freeModeStockExchangeConfig.insiderWindow.cooldownMinutes * 60 * 1000,
    inputCost: { cash: freeModeStockExchangeConfig.insiderWindow.costCleanCash },
    outputGain: {},
    heatGain: freeModeStockExchangeConfig.insiderWindow.heatGain,
    influenceChange: 0,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Insider Window aktivní. Burza ukazuje hlubší trend hints, ale zvedá financial inspection risk."
  },
  liquidity_injection: {
    actionId: "liquidity_injection",
    buildingType: "central_bank",
    label: "Likviditní injekce",
    description: "Okamžitě přidá clean cash podle velikosti čisté ekonomiky hráče a zvýší Financial Oversight risk.",
    durationMs: 0,
    cooldownMs: freeModeCentralBankConfig.liquidityInjection.cooldownMinutes * 60 * 1000,
    inputCost: {},
    outputGain: {},
    heatGain: freeModeCentralBankConfig.liquidityInjection.heatGain,
    influenceChange: -freeModeCentralBankConfig.liquidityInjection.costInfluence,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Centrální banka provedla likviditní injekci podle čisté ekonomiky hráče."
  },
  frozen_accounts: {
    actionId: "frozen_accounts",
    buildingType: "central_bank",
    label: "Zmrazené účty",
    description: "Na 8 minut zvýší ochranu clean cash, sníží pokuty a finanční ztráty, ale zhorší market fee.",
    durationMs: freeModeCentralBankConfig.frozenAccounts.durationMinutes * 60 * 1000,
    cooldownMs: freeModeCentralBankConfig.frozenAccounts.cooldownMinutes * 60 * 1000,
    inputCost: { cash: freeModeCentralBankConfig.frozenAccounts.costCleanCash },
    outputGain: {},
    heatGain: freeModeCentralBankConfig.frozenAccounts.heatGain,
    influenceChange: 0,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Zmrazené účty chrání rezervy, ale zhoršují poplatkovou stopu na marketu."
  },
  currency_intervention: {
    actionId: "currency_intervention",
    buildingType: "central_bank",
    label: "Kurzovní intervence",
    description: "Na 8 minut stabilizuje vybranou market kategorii a tlumí účinek Tržního tlaku z Burzy.",
    durationMs: freeModeCentralBankConfig.currencyIntervention.durationMinutes * 60 * 1000,
    cooldownMs: freeModeCentralBankConfig.currencyIntervention.cooldownMinutes * 60 * 1000,
    inputCost: { cash: freeModeCentralBankConfig.currencyIntervention.costCleanCash },
    outputGain: {},
    heatGain: freeModeCentralBankConfig.currencyIntervention.heatGain,
    influenceChange: -freeModeCentralBankConfig.currencyIntervention.costInfluence,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Centrální banka spustila kurzovní intervenci ve vybrané kategorii."
  },
  ...freeModeLobbyClubBuildingActions
};
