import type { ResolvedGameModeConfig } from "../../contracts/game-mode-config";
import { freeModeArcadeConfig } from "../../public/free-mode-arcade-config";
import { freeModeClinicConfig } from "../../public/free-mode-clinic-config";
import { freeModePowerStationConfig } from "../../public/free-mode-power-station-config";
import { freeModeRecyclingCenterConfig } from "../../public/free-mode-recycling-center-config";
import { freeModeSchoolConfig } from "../../public/free-mode-school-config";
import { freeModeSmugglingTunnelConfig } from "../../public/free-mode-smuggling-tunnel-config";

export const freeModeRecoveryBuildingActions: NonNullable<ResolvedGameModeConfig["balance"]["buildingActions"]> = {  open_channel: {
    actionId: "open_channel",
    buildingType: "smuggling_tunnel",
    label: "Otevřít kanál",
    description: "Na 15 minut globálně posílí dirty cash produkci Pašovacích tunelů a prodej Pouličních dealerů. Nestackuje se.",
    durationMs: freeModeSmugglingTunnelConfig.openChannel.durationMinutes * 60 * 1000,
    cooldownMs: freeModeSmugglingTunnelConfig.openChannel.cooldownMinutes * 60 * 1000,
    inputCost: { cash: freeModeSmugglingTunnelConfig.openChannel.costCleanCash },
    outputGain: {},
    heatGain: freeModeSmugglingTunnelConfig.openChannel.heatGain,
    influenceChange: 0,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Otevřený kanál krátkodobě zvedne tok špinavých peněz v tunelech. Pouliční dealeři prodávají výhodněji, ale roste riziko pouličního incidentu."
  },
  extract_losses: {
    actionId: "extract_losses",
    buildingType: "recycling_center",
    label: "Vytěžit ztráty",
    description: "Vrátí část neexpirovaných itemových ztrát ze salvage poolu. Nevrací populaci ani členy gangu.",
    durationMs: 0,
    cooldownMs: freeModeRecyclingCenterConfig.extractLosses.cooldownMinutes * 60 * 1000,
    inputCost: { cash: freeModeRecyclingCenterConfig.extractLosses.cleanCashCost },
    outputGain: {},
    heatGain: freeModeRecyclingCenterConfig.extractLosses.heatGain,
    influenceChange: 0,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Recyklační centrum vytěžilo část ztracených itemů ze šrotu."
  },
  stabilization_protocol: {
    actionId: "stabilization_protocol",
    buildingType: "clinic",
    label: "Stabilizační protokol",
    description: "Za clean cash vrátí část neexpirovaných ztrát z recovery poolu do gangu a skladu.",
    durationMs: 0,
    cooldownMs: freeModeClinicConfig.stabilizationProtocol.cooldownMinutes * 60 * 1000,
    inputCost: { cash: freeModeClinicConfig.stabilizationProtocol.cleanCashCost },
    outputGain: {},
    heatGain: freeModeClinicConfig.stabilizationProtocol.heatGain,
    influenceChange: 0,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Stabilizační protokol obnoví část nedávných ztrát. Recovery neprobíhá automaticky."
  },
  collect_population: {
    actionId: "collect_population",
    buildingType: "apartment_block",
    label: "Vybrat obyvatele",
    description: "Přesune lokálně uložené obyvatele z bytového bloku do globální populace hráče.",
    durationMs: 0,
    cooldownMs: 0,
    inputCost: {},
    outputGain: {},
    heatGain: 0,
    influenceChange: 0,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Vybere obyvatele z lokálního zásobníku bytového bloku."
  },
  evening_course: {
    actionId: "evening_course",
    buildingType: "school",
    label: "Večerní kurz",
    description: "Na 20 minut zrychlí nábor členů v bytových blocích. Nestackuje se.",
    durationMs: freeModeSchoolConfig.eveningCourse.durationMinutes * 60 * 1000,
    cooldownMs: freeModeSchoolConfig.eveningCourse.cooldownMinutes * 60 * 1000,
    inputCost: { cash: freeModeSchoolConfig.eveningCourse.costCleanCash },
    outputGain: {},
    heatGain: 0,
    influenceChange: 0,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Večerní kurz dočasně zvedne nábor členů v bytových blocích."
  },
  night_machines: {
    actionId: "night_machines",
    buildingType: "arcade",
    label: "Noční automaty",
    description: "Na 7 minut zvýší produkci Herny, vliv, heat a audit risk.",
    durationMs: freeModeArcadeConfig.nightMachines.durationMinutes * 60 * 1000,
    cooldownMs: freeModeArcadeConfig.nightMachines.cooldownMinutes * 60 * 1000,
    inputCost: {},
    outputGain: {},
    heatGain: 0,
    influenceChange: 0,
    effectModifiers: {
      cleanIncomeMultiplier: 1 + freeModeArcadeConfig.nightMachines.cleanIncomeBonusPct / 100,
      dirtyIncomeMultiplier: 1 + freeModeArcadeConfig.nightMachines.dirtyIncomeBonusPct / 100,
      influenceMultiplier: 1 + freeModeArcadeConfig.nightMachines.influenceBonusPct / 100,
      heatMultiplier: 1 + freeModeArcadeConfig.nightMachines.heatBonusPct / 100
    },
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Aktivuje Noční automaty. Boost se sám se sebou nestackuje."
  },
  backup_grid_switch: {
    actionId: "backup_grid_switch",
    buildingType: "power_station",
    label: "Přepnutí na záložní síť",
    description: "Dočasně zvýší infrastructure bonus a posílí kamery, alarm, Továrny a Zbrojovky.",
    durationMs: freeModePowerStationConfig.backupGridSwitch.durationMinutes * 60 * 1000,
    cooldownMs: freeModePowerStationConfig.backupGridSwitch.cooldownMinutes * 60 * 1000,
    inputCost: { cash: freeModePowerStationConfig.backupGridSwitch.cleanCashCost },
    outputGain: {},
    heatGain: freeModePowerStationConfig.backupGridSwitch.heatGain,
    influenceChange: 0,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Záložní síť aktivní. Infrastruktura a obranné systémy jsou dočasně posílené."
  },
  power_station_feed_production: {
    actionId: "power_station_feed_production",
    buildingType: "power_station",
    label: "Napájet výrobu",
    description: "Okamžitě přidá menší clean a dirty výnos z přesměrované výroby.",
    durationMs: 0,
    cooldownMs: 60 * 60 * 1000,
    inputCost: {},
    outputGain: { cash: 2000, "dirty-cash": 500 },
    heatGain: 10,
    influenceChange: 0,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Napájení výroby přidalo 2000 clean cash a 500 dirty cash. Heat +10."
  },
  power_station_reduce_heat: {
    actionId: "power_station_reduce_heat",
    buildingType: "power_station",
    label: "Snížit heat",
    description: "Serverově sníží heat districtu o 20 bodů.",
    durationMs: 0,
    cooldownMs: 60 * 60 * 1000,
    inputCost: {},
    outputGain: {},
    heatGain: -20,
    influenceChange: 0,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Energetická stanice stabilizovala provoz a snížila heat districtu o 20."
  },
  start_drug_sale: {
    actionId: "start_drug_sale",
    buildingType: "street_dealers",
    label: "Spustit prodej",
    description: "Použije globální slot Pouličních dealerů k prodeji látky vyrobené v Drug Labu za dirty cash.",
    durationMs: 0,
    cooldownMs: 0,
    inputCost: {},
    outputGain: {},
    heatGain: 0,
    influenceChange: 0,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Pouliční dealeři spustili prodej přes vybraný slot."
  },
  street_dealers_collect_hot_cash: {
    actionId: "street_dealers_collect_hot_cash",
    buildingType: "street_dealers",
    label: "Vybrat hot cash",
    description: "Okamžitě vybere menší balík špinavých peněz z ulice.",
    durationMs: 0,
    cooldownMs: 10 * 60 * 1000,
    inputCost: {},
    outputGain: { "dirty-cash": 280 },
    heatGain: 3,
    influenceChange: 0,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Pouliční dealeři vybrali 280 dirty cash. Heat +3."
  },
  street_dealers_move_stash: {
    actionId: "street_dealers_move_stash",
    buildingType: "street_dealers",
    label: "Přesunout stash",
    description: "Spotřebuje 3 biomass a promění přesunutý stash na dirty cash.",
    durationMs: 0,
    cooldownMs: 10 * 60 * 1000,
    inputCost: { biomass: 3 },
    outputGain: { "dirty-cash": 1000 },
    heatGain: 1,
    influenceChange: 0,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Stash přesunut: -3 biomass, +1000 dirty cash, heat +1."
  }
};
