import type { ResolvedGameModeConfig } from "../../contracts/game-mode-config";
import { baseCooldownMsForFinalMinutes } from "./free-mode-timing";

export const freeModeProductionBuildingActions: NonNullable<ResolvedGameModeConfig["balance"]["buildingActions"]> = {
  produce_chemicals: {
    actionId: "produce_chemicals",
    buildingType: "pharmacy",
    label: "Produce Chemicals",
    description: "Vyrobi zakladni chemikalie pro leky a lab.",
    durationMs: 0,
    cooldownMs: baseCooldownMsForFinalMinutes(2),
    inputCost: {},
    outputGain: { chemicals: 6 },
    heatGain: 1,
    influenceChange: 0,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Lekarna vyrobila chemicals."
  },
  produce_biomass: {
    actionId: "produce_biomass",
    buildingType: "pharmacy",
    label: "Produce Biomass",
    description: "Vyrobi biomasu pro leky a drogy.",
    durationMs: 0,
    cooldownMs: baseCooldownMsForFinalMinutes(2),
    inputCost: {},
    outputGain: { biomass: 4 },
    heatGain: 1,
    influenceChange: 0,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Lekarna vyrobila biomass."
  },
  produce_stim_pack: {
    actionId: "produce_stim_pack",
    buildingType: "pharmacy",
    label: "Produce Stim Pack",
    description: "Prevede chemicals a biomass na Stim Pack.",
    durationMs: 0,
    cooldownMs: baseCooldownMsForFinalMinutes(4),
    inputCost: { chemicals: 2, biomass: 1 },
    outputGain: { "stim-pack": 1 },
    heatGain: 2,
    influenceChange: 1,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Lekarna vyrobila Stim Pack."
  },
  produce_neon_dust: {
    actionId: "produce_neon_dust",
    buildingType: "drug_lab",
    label: "Produce Neon Dust",
    description: "Syntetizuje Neon Dust.",
    durationMs: 0,
    cooldownMs: baseCooldownMsForFinalMinutes(4),
    inputCost: { chemicals: 1 },
    outputGain: { "neon-dust": 2 },
    heatGain: 3,
    influenceChange: 1,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Drug Lab vyrobil Neon Dust."
  },
  produce_pulse_shot: {
    actionId: "produce_pulse_shot",
    buildingType: "drug_lab",
    label: "Produce Pulse Shot",
    description: "Uvari Pulse Shot.",
    durationMs: 0,
    cooldownMs: baseCooldownMsForFinalMinutes(5),
    inputCost: { chemicals: 2, biomass: 1 },
    outputGain: { "pulse-shot": 1 },
    heatGain: 3,
    influenceChange: 1,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Drug Lab vyrobil Pulse Shot."
  },
  produce_velvet_smoke: {
    actionId: "produce_velvet_smoke",
    buildingType: "drug_lab",
    label: "Produce Velvet Smoke",
    description: "Vyrobi Velvet Smoke.",
    durationMs: 0,
    cooldownMs: baseCooldownMsForFinalMinutes(6),
    inputCost: { biomass: 2 },
    outputGain: { "velvet-smoke": 2 },
    heatGain: 2,
    influenceChange: 1,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Drug Lab vyrobil Velvet Smoke."
  },
  produce_tech_core: {
    actionId: "produce_tech_core",
    buildingType: "factory",
    label: "Produce Tech Core",
    description: "Sestavi Tech Core z dilu.",
    durationMs: 0,
    cooldownMs: baseCooldownMsForFinalMinutes(6),
    inputCost: { "metal-parts": 2 },
    outputGain: { "tech-core": 1 },
    heatGain: 2,
    influenceChange: 0,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Tovarna vyrobila Tech Core."
  },
  produce_combat_module: {
    actionId: "produce_combat_module",
    buildingType: "factory",
    label: "Vyrobit bojovy modul",
    description: "Vyrobi bojovy modul jako soucastku pro pokrocile vybaveni.",
    durationMs: 0,
    cooldownMs: baseCooldownMsForFinalMinutes(12),
    inputCost: { "metal-parts": 2, "tech-core": 1 },
    outputGain: { "combat-module": 1 },
    heatGain: 3,
    influenceChange: 1,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Tovarna vyrobila bojovy modul."
  },
  armory_craft_weapons: {
    actionId: "armory_craft_weapons",
    buildingType: "armory",
    label: "Vyrobit vyzbrojni modul",
    description: "Vyrobi vyzbrojni modul ve zbrojovce jako soucastku pro dalsi vybaveni.",
    durationMs: 0,
    cooldownMs: baseCooldownMsForFinalMinutes(12),
    inputCost: { "metal-parts": 2 },
    outputGain: { "combat-module": 1 },
    heatGain: 3,
    influenceChange: 1,
    requiredOwner: true,
    allowedIfContested: false,
    reportText: "Zbrojovka vyrobila vyzbrojni modul."
  }
};
