/**
 * Responsibility: Central registry of well-known core event type keys.
 * Belongs here: shared event identifiers used by handlers and projections.
 * Does not belong here: runtime event queues or websocket topics.
 */
export const CORE_EVENT_TYPES = {
  districtSpied: "district-spied",
  districtAttacked: "district-attacked",
  districtCaptured: "district-captured",
  districtOccupyResolved: "district-occupy-resolved",
  districtHeisted: "district-heisted",
  districtRobbed: "district-robbed",
  defensePlaced: "defense-placed",
  defenseRemoved: "defense-removed",
  trapPlaced: "trap-placed",
  trapTriggered: "trap-triggered",
  buildingActionResolved: "building-action-resolved",
  buildingUpgraded: "building-upgraded",
  allianceCreated: "alliance-created",
  allianceJoined: "alliance-joined",
  allianceInviteCreated: "alliance-invite-created",
  allianceInviteResponded: "alliance-invite-responded",
  allianceChatMessageSent: "alliance-chat-message-sent",
  bountyCancelled: "bounty-cancelled",
  bountyClaimed: "bounty-claimed",
  bountyCreated: "bounty-created",
  bountyExpired: "bounty-expired",
  buildingPlaced: "building-placed",
  productionCollected: "production-collected",
  itemProcessingStarted: "item-processing-started",
  itemCrafted: "item-crafted",
  marketTransactionResolved: "market-transaction-resolved",
  policeRaidAcknowledged: "police-raid-acknowledged",
  policeRaidExpired: "police-raid-expired",
  policeRaidResolved: "police-raid-resolved",
  policeRaidTriggered: "police-raid-triggered",
  policeWarningIssued: "police-warning-issued",
  playerEliminated: "player-eliminated",
  playerBoostActivated: "player-boost-activated",
  playerBoostExpired: "player-boost-expired",
  playerBoostConsumed: "player-boost-consumed",
  finalLockdownStarted: "final-lockdown-started",
  finalLockdownResolved: "final-lockdown-resolved",
  commandApplied: "command-applied",
  notificationCreated: "notification-created"
} as const;
