export {
  DISTRICT_BUILDING_PACKAGE_POOLS,
  DISTRICT_FIXED_BUILDING_PACKAGES_BY_DISTRICT_ID,
  DOWNTOWN_FIXED_BUILDING_PACKAGES_BY_DISTRICT_ID,
  formatDistrictBuildingTierLabel
} from "../../data/districtPools.js";

export const DISTRICT_MINUTE_INCOME_RULES_EMPIRE2 = Object.freeze({
  resident: Object.freeze({ clean: 2, dirty: 0.5 }),
  economy: Object.freeze({ clean: 3, dirty: 1 }),
  industrial: Object.freeze({ clean: 3, dirty: 1 }),
  park: Object.freeze({ clean: 2, dirty: 1 }),
  downtown: Object.freeze({ clean: 5, dirty: 2 })
});

export const DISTRICT_BUILDING_MINUTE_INCOME_RULES_EMPIRE2 = Object.freeze({
  "Autosalon": Object.freeze({ clean: 2145 / 60, dirty: 650 / 60 }),
  "Fitness Club": Object.freeze({ clean: 72, dirty: 0 }),
  Herna: Object.freeze({ clean: 30, dirty: 20 }),
  Kasino: Object.freeze({ clean: 4500 / 60, dirty: 2500 / 60 }),
  "Lékárna": Object.freeze({ clean: 0, dirty: 0 }),
  "Obchodní centrum": Object.freeze({ clean: 3700 / 60, dirty: 22 }),
  Restaurace: Object.freeze({ clean: 38, dirty: 0 }),
  "Směnárna": Object.freeze({ clean: 70, dirty: 95 }),
  "Energetická stanice": Object.freeze({ clean: 2780 / 60, dirty: 780 / 60 }),
  Sklad: Object.freeze({ clean: 45, dirty: 0 }),
  Skladiště: Object.freeze({ clean: 45, dirty: 0 }),
  "Továrna": Object.freeze({ clean: 1, dirty: 0.2 }),
  "Zbrojovka": Object.freeze({ clean: 1.2, dirty: 0.5 }),
  "Bytový blok": Object.freeze({ clean: 0, dirty: 0 }),
  Garage: Object.freeze({ clean: 42, dirty: 0 }),
  Klinika: Object.freeze({ clean: 3100 / 60, dirty: 0 }),
  "Rekrutační centrum": Object.freeze({ clean: 35, dirty: 0 }),
  "Škola": Object.freeze({ clean: 18, dirty: 0 }),
  "Drug lab": Object.freeze({ clean: 1.5, dirty: 2 }),
  "Pašovací tunel": Object.freeze({ clean: 0, dirty: 54 }),
  "Pouliční dealeři": Object.freeze({ clean: 0, dirty: 36 }),
  "Strip club": Object.freeze({ clean: 75, dirty: 65 }),
  "Večerka": Object.freeze({ clean: 32, dirty: 18 }),
  "Recyklační centrum": Object.freeze({ clean: 40, dirty: 0 }),
  Burza: Object.freeze({ clean: 220, dirty: 0 }),
  "Centrální banka": Object.freeze({ clean: 160, dirty: 0, heat: 0.1, influence: 0.35 }),
  "Letiště": Object.freeze({ clean: 180, dirty: 45 }),
  "Lobby klub": Object.freeze({ clean: 95, dirty: 0, heat: 0.1, influence: 0.65 }),
  "Lobby Club": Object.freeze({ clean: 95, dirty: 0, heat: 0.1, influence: 0.65 }),
  "Magistrát": Object.freeze({ clean: 130, dirty: 0 }),
  "VIP Salonek": Object.freeze({ clean: 105, dirty: 30 }),
  "VIP salonek": Object.freeze({ clean: 105, dirty: 30 }),
  Parlament: Object.freeze({ clean: 22, dirty: 3 }),
  "Přístav": Object.freeze({ clean: 26, dirty: 8.5 }),
  Soud: Object.freeze({ clean: 105, dirty: 0, heat: 0.08, influence: 0.72 }),
  "VIP salonek": Object.freeze({ clean: 8, dirty: 22 })
});

export const DISTRICT_BUILDING_MINUTE_HEAT_RULES_EMPIRE2 = Object.freeze({
  Autosalon: Object.freeze({ heat: 60 / (60 * 24) }),
  "Fitness Club": Object.freeze({ heat: 0.04 }),
  Herna: Object.freeze({ heat: 0.12 }),
  "Obchodní centrum": Object.freeze({ heat: 65 / (60 * 24) }),
  Kasino: Object.freeze({ heat: 150 / (60 * 24) }),
  Restaurace: Object.freeze({ heat: 0.04 }),
  "Směnárna": Object.freeze({ heat: 70 / 1440 }),
  "Pašovací tunel": Object.freeze({ heat: 0.07 }),
  "Pouliční dealeři": Object.freeze({ heat: 0.06 }),
  Burza: Object.freeze({ heat: 0.18 }),
  "Letiště": Object.freeze({ heat: 0.2 }),
  "Magistrát": Object.freeze({ heat: 0.12 }),
  "Lobby klub": Object.freeze({ heat: 0.1 }),
  "Lobby Club": Object.freeze({ heat: 0.1 }),
  Soud: Object.freeze({ heat: 0.08 }),
  "VIP Salonek": Object.freeze({ heat: 0.13 }),
  "VIP salonek": Object.freeze({ heat: 0.13 }),
  "Strip club": Object.freeze({ heat: 0.18 }),
  Sklad: Object.freeze({ heat: 0.06 }),
  Skladiště: Object.freeze({ heat: 0.06 }),
  Garage: Object.freeze({ heat: 0.06 }),
  Klinika: Object.freeze({ heat: 85 / (60 * 24) }),
  "Rekrutační centrum": Object.freeze({ heat: 0.07 }),
  "Škola": Object.freeze({ heat: 0 }),
  "Večerka": Object.freeze({ heat: 0.05 }),
  "Recyklační centrum": Object.freeze({ heat: 0.08 })
});

export const DISTRICT_BUILDING_MINUTE_INFLUENCE_RULES_EMPIRE2 = Object.freeze({
  Autosalon: Object.freeze({ influence: 1 / 60 }),
  "Fitness Club": Object.freeze({ influence: 0 }),
  Herna: Object.freeze({ influence: 80 / (60 * 24) }),
  "Obchodní centrum": Object.freeze({ influence: 95 / (60 * 24) }),
  Kasino: Object.freeze({ influence: 110 / (60 * 24) }),
  Restaurace: Object.freeze({ influence: 0.12 }),
  "Směnárna": Object.freeze({ influence: 60 / 1440 }),
  "Pašovací tunel": Object.freeze({ influence: 0 }),
  "Pouliční dealeři": Object.freeze({ influence: 0 }),
  Burza: Object.freeze({ influence: 0.45 }),
  "Letiště": Object.freeze({ influence: 0.2 }),
  "Magistrát": Object.freeze({ influence: 0.85 }),
  "Lobby klub": Object.freeze({ influence: 0.65 }),
  "Lobby Club": Object.freeze({ influence: 0.65 }),
  Soud: Object.freeze({ influence: 0.72 }),
  "VIP Salonek": Object.freeze({ influence: 0.48 }),
  "VIP salonek": Object.freeze({ influence: 0.48 }),
  "Strip club": Object.freeze({ influence: 0.38 }),
  Sklad: Object.freeze({ influence: 0 }),
  Skladiště: Object.freeze({ influence: 0 }),
  Garage: Object.freeze({ influence: 0 }),
  Klinika: Object.freeze({ influence: 0 }),
  "Rekrutační centrum": Object.freeze({ influence: 0 }),
  "Škola": Object.freeze({ influence: 0.05 }),
  "Večerka": Object.freeze({ influence: 0.1 }),
  "Recyklační centrum": Object.freeze({ influence: 0 })
});
