export const ONBOARDING_VERSION = "v2";

export const ONBOARDING_REQUIRED_STEP_IDS = Object.freeze([
  "welcome",
  "win-condition",
  "your-district",
  "district-stats",
  "buildings",
  "cash",
  "production",
  "people",
  "heat",
  "day-night",
  "neighbor-districts",
  "spy",
  "robbery",
  "occupy-attack",
  "traps",
  "city-feed",
  "market",
  "alliance",
  "elimination",
  "danger-zone",
  "downtown",
  "next-plan"
]);

export const ONBOARDING_STEPS = Object.freeze([
  Object.freeze({
    id: "welcome",
    title: "Vítej, králi kanálu",
    body: "Vítej v Empire Streets, ó statečný troubo s ambicí. Tohle město není hřiště. Je to neonová žumpa, která ti zatleská, až uklouzneš ve vlastní špíně.",
    targetSelector: null,
    placement: "bottom-right",
    completionCondition: "manual",
    fallbackBody: null,
    canSkip: true,
    highlightType: "none",
    optionalActionHint: "Drž hubu a koukej. Město právě rozhoduje, jestli jsi hrozba, nebo snídaně.",
    detail: "Zapamatuj si: nejsi vyvolený. Jsi další problém s loginem.",
    task: "Vlez dovnitř, ať se tragédie může rozjet.",
    cta: "Jdu dovnitř"
  }),
  Object.freeze({
    id: "win-condition",
    title: "Koruna pro největšího hajzla",
    body: "Cíl je jednoduchý, až je to urážlivé: přežij čistky, ber území a drž 75 % aktivního města. Sám, nebo přes alianci. Kdo drží mapu, píše zákony. Ostatní píšou výmluvy.",
    targetSelector: "[data-br-info-open], [data-leaderboard-popup-open]",
    placement: "bottom-right",
    completionCondition: "manual",
    fallbackBody: "Win condition se nezměnila, můj malý stratégu z popelnice: přežij a urvi 75 % aktivních districtů. Destroyed district je mrtvý kus betonu a počítá se jen podle core pravidel.",
    canSkip: true,
    highlightType: "objective",
    optionalActionHint: "75 % města může vzít hráč nebo aliance. Demokracie zemřela, gratulujeme.",
    detail: "Zapamatuj si: cash je hezký. Území je trůn. Nepleť si kasičku s korunou.",
    task: "Pochop cíl války."
  }),
  Object.freeze({
    id: "your-district",
    title: "Tvoje první smradlavá díra",
    body: "Hle, tvůj první district. Není krásný, není bezpečný a pravděpodobně by neprošel hygienou. Ale je tvůj. Bez něj nejsi boss, jen účet s názorem.",
    targetSelector: "[data-mount-role=\"map\"], [data-district-canvas], canvas",
    placement: "bottom-right",
    completionCondition: "district:own-opened",
    fallbackBody: "Server zatím neukázal tvůj district. Až ho dostaneš, začne tvůj slavný pád vzhůru.",
    canSkip: true,
    highlightType: "map",
    optionalActionHint: "Klikni na svoje území. Ano, to je ten kus bídy s tvým jménem.",
    detail: "Zapamatuj si: impérium nezačíná proslovem. Začíná tím, že vlastníš kus bordelu.",
    task: "Klikni na svůj district."
  }),
  Object.freeze({
    id: "district-stats",
    title: "Čísla, ty nešťastníku",
    body: "District není obrázek pro turisty s latte. Má vlastníka, zone, heat, influence, budovy a sousedy. Když to nečteš, nehraješ strategii. Jen klikáš a doufáš jako idiot.",
    targetSelector: "[data-district-popup-card], [data-district-popup-status], .district-popup-summary-grid",
    placement: "right",
    completionCondition: "district:stats-read",
    fallbackBody: "Detail districtu teď není dostupný. Přesto platí: owner, zone, heat, influence, buildings a sousedé rozhodují, jestli jsi plánovač, nebo chodící fail.",
    canSkip: true,
    highlightType: "panel",
    optionalActionHint: "Přečti vlastníka, zone, heat, influence a budovy.",
    detail: "Zapamatuj si: sousedství není sociální koncept. Je to mapa toho, koho můžeš zítra okrást.",
    task: "Zkontroluj statistiky districtu."
  }),
  Object.freeze({
    id: "buildings",
    title: "Budovy nejsou tapeta",
    body: "Budovy jsou orgány tvého impéria, což zní vznešeně, dokud si nevšimneš, že celé tělo smrdí. Dělají peníze, materiál, influence, heat a speciální akce. Ignoruj je a chcípneš elegantně, ale blbě.",
    targetSelector: "[data-district-popup-buildings], [data-district-popup-buildings-list], #buildings-card",
    placement: "right",
    completionCondition: "building:opened",
    fallbackBody: "Budovy najdeš v detailu districtu nebo pod tlačítkem Budovy. Pokud panel není dostupný, vezmi si z toho poučení: bez budov je impérium jen drahý squat.",
    canSkip: true,
    highlightType: "panel",
    optionalActionHint: "Otevři první budovu a zjisti, jestli vydělává, nebo jen zabírá místo.",
    detail: "Zapamatuj si: income, heat, influence, produkce a akce tečou přes budovy. Ano, musíš číst.",
    task: "Otevři detail první budovy."
  }),
  Object.freeze({
    id: "cash",
    title: "Prachy: čisté a svinské",
    body: "Clean cash je slušný oblek na mrtvole. Dirty cash je rychlá špína v igelitce. Vydělá víc, ale přinese heat, kontroly a ten krásný moment, kdy si řekneš: do prdele, tohle byl nápad.",
    targetSelector: "[data-topbar-clean-money], [data-topbar-dirty-money], .game-resource-strip",
    placement: "bottom",
    completionCondition: "income:tick",
    fallbackBody: "Horní lišta s cash teď není v dosahu. Pravidlo pro začátečního zločince: clean tě drží stabilně, dirty tě žene rychleji a zároveň ti lepí terč na záda.",
    canSkip: true,
    highlightType: "resource",
    optionalActionHint: "Počkej na income tick, nebo použij collect, když je dostupný.",
    detail: "Zapamatuj si: laundering a black market jsou užitečné dveře. Za některými stojí zisk, za jinými facka od systému.",
    task: "Zkontroluj cash v horní liště."
  }),
  Object.freeze({
    id: "production",
    title: "Továrna na špatná rozhodnutí",
    body: "Chemicals, biomass, metal parts, tech core. Nejsou to barevné bonbony pro manažera s tabulkou. Je to palivo pro zbraně, drogy, boosty a další věci, které úředník nazve problémem.",
    targetSelector: "[data-district-building-detail-collect], [data-district-popup-buildings-list], #building-shortcut-grid",
    placement: "right",
    completionCondition: "production:selected",
    fallbackBody: "Produkční slot teď není dostupný. Pokud district nemá production budovu, gratuluju, tvůj průmyslový plán je zatím básnička bez rýmu.",
    canSkip: true,
    highlightType: "panel",
    optionalActionHint: "Vyber nebo seber produkci, pokud to hra dovolí.",
    detail: "Zapamatuj si: storage cap je strop. Když ho ignoruješ, nehospodaříš. Jen vyrábíš ztrátu s fanfárou.",
    task: "Najdi production nebo collect."
  }),
  Object.freeze({
    id: "people",
    title: "Maso s výplatou",
    body: "Prachy cinkají, ale ulice vyhrávají lidi. Population a gang members jsou tvoje munice s botama. Bez nich posíláš do akce jen ego, a ego neumí držet district.",
    targetSelector: "[data-gang-members], [data-gang-population], [data-player-gang-members], #profile-gang-card",
    placement: "left",
    completionCondition: "people:read",
    fallbackBody: "Population nebo gang members panel teď nesvítí. Pointa je pořád stejná: bez lidí nejsou útoky, obrana ani tvůj slavný plán světové nadvlády.",
    canSkip: true,
    highlightType: "resource",
    optionalActionHint: "Zkontroluj gang members a population.",
    detail: "Zapamatuj si: každý ztracený člen je tempo v hajzlu. A tempo je v téhle hře kyslík.",
    task: "Přečti stav lidí."
  }),
  Object.freeze({
    id: "heat",
    title: "Heat: potlesk policie",
    body: "Heat je smrad po tvých průserech. Čím víc špinavých věcí děláš, tím víc město zvedá obočí a policie si obléká těžké boty. Pak přijdou dveře. Tvoje dveře.",
    targetSelector: "[data-gang-heat], .profile-heat-panel",
    placement: "left",
    completionCondition: "heat:opened",
    fallbackBody: "Heat badge teď není vidět. Vysoký heat znamená, že z chytrého plánu může být velmi veřejná sračka.",
    canSkip: true,
    highlightType: "danger",
    optionalActionHint: "Otevři nebo přečti heat badge.",
    detail: "Zapamatuj si: player heat a district heat nejsou nálada UI. Je to účet za tvoje veselá rozhodnutí.",
    task: "Zkontroluj heat."
  }),
  Object.freeze({
    id: "day-night",
    title: "Den udává, noc krade",
    body: "Ve dne kamery vidí víc a legální byznys se tváří, že má duši. V noci ožije black market, heisty a drby. Noc je skvělá, pokud máš plán. Pokud ne, je to jen tma s účtenkou.",
    targetSelector: ".map-phase-toolbar, [data-game-phase-toggle], [data-map-phase-toggle]",
    placement: "bottom",
    completionCondition: "day-night:opened",
    fallbackBody: "Day/night read model teď není napojený. Překlad pro unavené mozky: den je kontrola, noc je chaos a příležitost k průseru se ziskem.",
    canSkip: true,
    highlightType: "system",
    optionalActionHint: "Sleduj fázi dne. Timing je rozdíl mezi výdělkem a trapnou smrtí.",
    detail: "Zapamatuj si: day/night mění riziko, zisk a kvalitu informací. Město má směny, ty máš následky.",
    task: "Zkontroluj fázi dne."
  }),
  Object.freeze({
    id: "neighbor-districts",
    title: "Sousedé: menu dne",
    body: "Neexpanduješ náhodně, ó dobyvateli s prstem na myši. Město má spoje a ty jdeš přes sousedy. Slabý soused je oběd. Silný soused je cedule: zkus to a budeš vtip.",
    targetSelector: "[data-mount-role=\"map\"], [data-district-canvas], canvas",
    placement: "bottom-right",
    completionCondition: "district:neighbor-opened",
    fallbackBody: "Sousední district teď není v read modelu. Vyber nejbližší cizí blok a zjisti, jestli jsi lovec, nebo jen hlavní chod.",
    canSkip: true,
    highlightType: "map",
    optionalActionHint: "Klikni na souseda. Než ho sežere jiný hladový blbec.",
    detail: "Zapamatuj si: bez adjacency je expanze jen hysterické ťukání do mapy.",
    task: "Vyber sousední district."
  }),
  Object.freeze({
    id: "spy",
    title: "Špehuj, než se ztrapníš",
    body: "Špehování je rozdíl mezi plánem a epickou ostudou. Ukáže typ, obranu, riziko a někdy past. Kdo jde naslepo, hraje tragédii, ve které je hlavní role mrtvola.",
    targetSelector: "[data-district-action-id=\"spy\"], [data-spy-confirm], [data-district-actions]",
    placement: "right",
    completionCondition: "spy:opened",
    fallbackBody: "Špehování se ukáže, až bude správný cíl a podmínky. Do té doby si pamatuj: slepý útok není odvaha. Je to účet za blbost.",
    canSkip: true,
    highlightType: "action",
    optionalActionHint: "Otevři spy na sousední district.",
    detail: "Zapamatuj si: success, partial a fail jsou informace. Jen idiot vyhodí mapu, protože není hezká.",
    task: "Otevři spy."
  }),
  Object.freeze({
    id: "robbery",
    title: "Vykrást, ne adoptovat",
    body: "Vykradení nebere district. Jen tam vpadneš, sebereš cash a resources a modlíš se, aby se tvoji lidi vrátili s víc než traumatem. Rychlý zisk, rychlý průser, klasická poezie města.",
    targetSelector: "[data-district-action-id=\"rob\"], [data-district-action-id=\"heist\"], [data-robbery-confirm], [data-district-actions]",
    placement: "right",
    completionCondition: "robbery:opened",
    fallbackBody: "Vykradení potřebuje vhodný cíl. Spy nemusí být povinné, ale bez intel preview je to ruleta pro lidi, co si myslí, že štěstí je strategie.",
    canSkip: true,
    highlightType: "action",
    optionalActionHint: "Otevři vykradení a přečti risk preview.",
    detail: "Zapamatuj si: loot, ztráty a heat. Tři akty malé špinavé tragédie.",
    task: "Otevři vykradení."
  }),
  Object.freeze({
    id: "occupy-attack",
    title: "Útok: teď už kradeš mapu",
    body: "Krádež tě nakrmí. Útok tě zvětší. Chceš vyhrát? Ber district za districtem a přestaň se tvářit, že morální dilema je herní mechanika. Zbraně, obrana, pasti, cooldowny - všechno tě může kopnout do zubů.",
    targetSelector: "[data-district-action-id=\"attack\"], [data-district-action-id=\"occupy\"], [data-district-actions]",
    placement: "right",
    completionCondition: "attack:opened",
    fallbackBody: "Attack nebo occupy panel se otevře jen u cíle, který dovolí server. Core rozhoduje. Frontend je jen poslíček se špatnými zprávami.",
    canSkip: true,
    highlightType: "danger",
    optionalActionHint: "Otevři attack nebo occupy panel.",
    detail: "Zapamatuj si: capture je růst. Destroyed district je spálená šance, pokud jsi to neplánoval. A ty plánuješ, že jo?",
    task: "Otevři bojový panel."
  }),
  Object.freeze({
    id: "traps",
    title: "Pasti: komedie bolesti",
    body: "Past je tichá svině s dobrým načasováním. Leží v districtu a čeká, až někdo přijde zahrát hrdinu. Pak přijde bum, pláč a krásné ticho po cizím egu.",
    targetSelector: "[data-district-action-id=\"trap\"], [data-district-actions]",
    placement: "right",
    completionCondition: "trap:opened",
    fallbackBody: "Trap akce teď není dostupná. Pravidlo je jednoduché: past trestá lidi, kteří si mysleli, že dveře jsou pozvánka.",
    canSkip: true,
    highlightType: "danger",
    optionalActionHint: "Najdi toxic trap v akcích districtu.",
    detail: "Zapamatuj si: dobrá past nemusí mluvit. Stačí, že někdo jiný začne křičet.",
    task: "Zkontroluj past."
  }),
  Object.freeze({
    id: "city-feed",
    title: "Drby z kanálu",
    body: "City feed je městský dvorní šašek po lobotomii: někdy pravda, někdy drb, někdy poetická blbost v plášti z dat. Ignoruj ho a budeš poslední, kdo zjistí, proč hoříš.",
    targetSelector: "[data-building-action-feed], [data-district-popup-gossip], [data-district-popup-gossip-list]",
    placement: "left",
    completionCondition: "city-feed:opened",
    fallbackBody: "Feed teď mlčí. Až se otevře, rozliš confirmed events, rumors a truthiness. Město lže, ale často lže směrem k užitečné pravdě.",
    canSkip: true,
    highlightType: "intel",
    optionalActionHint: "Přečti poslední události nebo drby.",
    detail: "Zapamatuj si: feed je intel z kanálu. Smrdí, ale někdy ti zachrání krk.",
    task: "Zkontroluj city feed."
  }),
  Object.freeze({
    id: "market",
    title: "Bazar zoufalých géniů",
    body: "Market je místo, kde zoufalí platí moc a chytří se tváří, že to byla ekonomická vize. Black market je dražší, špinavější a nebezpečnější, tedy přesně proto ho budeš potřebovat.",
    targetSelector: "[data-market-popup-open], [data-market-popup], #market-card",
    placement: "left",
    completionCondition: "market:opened",
    fallbackBody: "Market UI teď není dostupné. Počítej s normal marketem, black market riskem, player listings a cenami, které skáčou jako opilý prorok.",
    canSkip: true,
    highlightType: "resource",
    optionalActionHint: "Otevři bazar.",
    detail: "Zapamatuj si: scarce resources jsou zbraň. Kdo prodá ve správný čas, směje se i v pekle.",
    task: "Otevři market."
  }),
  Object.freeze({
    id: "alliance",
    title: "Aliance: přátelé s noži",
    body: "Aliance ti může dát štít, tlak a cestu k 75 %. Ale není to rodina. Je to banda lidí, co se zatím rozhodla nebodnout tě do zad, protože se jim hodíš.",
    targetSelector: "[data-alliance-popup-open], #alliance-btn, [data-gang-alliance]",
    placement: "left",
    completionCondition: "alliance:opened",
    fallbackBody: "Alliance UI teď není dostupné. Aliance může vyhrát přes 75 %, ale tvoji osobní slabost nevypere. Na to není dost aviváže ani zrady.",
    canSkip: true,
    highlightType: "system",
    optionalActionHint: "Otevři aliance nebo profil gangu.",
    detail: "Zapamatuj si: alliance control je moc. Být slabý člen je pořád pozvánka k problému.",
    task: "Zkontroluj alianci."
  }),
  Object.freeze({
    id: "elimination",
    title: "Čistka, ó radosti",
    body: "Každé čtyři hodiny město smaže nejslabšího aktivního hráče. První řez přijde po osmi hodinách. Mezi 00:00 a 06:00 se nevyhazuje, protože i digitální kat má pracovní dobu. Pak zase šup na popraviště.",
    targetSelector: "[data-br-info-open], #battle-royale-info-modal",
    placement: "bottom",
    completionCondition: "elimination:opened",
    fallbackBody: "Elimination read model teď nesvítí. Pravidlo je pořád stejné: slabí mizí. Defeated znamená, že server ti řekl dobrou noc a zabouchl víko.",
    canSkip: true,
    highlightType: "danger",
    optionalActionHint: "Zkontroluj Battle Royale info a další eliminaci.",
    detail: "Zapamatuj si: posledních 8 dohraje finále. Do té doby je čas kat s hodinkami.",
    task: "Přečti eliminační stav."
  }),
  Object.freeze({
    id: "danger-zone",
    title: "Danger zone, ne wellness",
    body: "Jestli jsi v danger zone, nebreč do kapuce. Získej district, zvedni influence, posil budovy a ukaž aktivitu. Jinak tě město sežere a ještě ti vystaví fakturu za úklid.",
    targetSelector: "[data-br-info-open], #battle-royale-info-modal, [data-leaderboard-popup-open]",
    placement: "bottom",
    completionCondition: "danger-zone:opened",
    fallbackBody: "Danger zone data teď nejsou dostupná. Hlavní váha je území; influence, buildings a resources pomáhají. Cash bez mapy je jen pozlacená sračka s dobrým PR.",
    canSkip: true,
    highlightType: "danger",
    optionalActionHint: "Najdi svůj risk: safe, danger nebo critical.",
    detail: "Zapamatuj si: aliance pomůže, ale pokud jsi slabý sám o sobě, jsi jen chráněná katastrofa.",
    task: "Zkontroluj svůj risk."
  }),
  Object.freeze({
    id: "downtown",
    title: "Downtown: drahá past",
    body: "Downtown není výlet pro influencery. Burza, Magistrát, Soud, Letiště, Banka - to jsou páky, co lámou server. Kdo je drží, netlačí na mapu. Tlačí všem prstem do oka.",
    targetSelector: "[data-mount-role=\"map\"], #building-shortcut-grid, #buildings-card",
    placement: "bottom-right",
    completionCondition: "downtown:read",
    fallbackBody: "Vzácné budovy teď nejsou vidět. Až je najdeš, nechovej se k nim jako k obyčejným barákům. Jsou to drahé důvody, proč se lidi začnou nenávidět.",
    canSkip: true,
    highlightType: "map",
    optionalActionHint: "Hledej Downtown a high-value building sety.",
    detail: "Zapamatuj si: court, city hall, stock exchange, central bank, airport, port a VIP lounge jsou serverové páky. A páky jsou od toho, aby někomu skříply prsty.",
    task: "Najdi high-value cíl."
  }),
  Object.freeze({
    id: "next-plan",
    title: "A teď nebuď tragéd",
    body: "Teď víš dost, abys nebyl úplně v prdeli. Drž district, sbírej income, hlídej heat, špehuj sousedy, ber slabé cíle a nepadni do danger zone. Město nečeká na tvůj charakterový vývoj.",
    targetSelector: "[data-mount-role=\"map\"], #game-root",
    placement: "bottom-right",
    completionCondition: "manual",
    fallbackBody: "Mapa teď mlčí. Plán zůstává stejný: district, income, heat, soused, rozhodnutí, eliminace. Ano, je to práce. Tragédie má administrativu.",
    canSkip: true,
    highlightType: "objective",
    optionalActionHint: "Klikni vlastní district, zkontroluj budovy, seber produkci, sleduj heat, najdi souseda a rozhodni: spy, vykrást, nebo útočit.",
    detail: "Checklist: území, budovy, produkce, heat, soused, akce, eliminace, útěk z danger zone. Krásná špína, že?",
    task: "Jdi pro město.",
    cta: "Jdu pro město"
  })
]);

export function getOnboardingStep(stepId) {
  return ONBOARDING_STEPS.find((step) => step.id === stepId) || null;
}

export function getOnboardingStepIndex(stepId) {
  const index = ONBOARDING_STEPS.findIndex((step) => step.id === stepId);
  return index >= 0 ? index : 0;
}

export function getOnboardingTargetSelector(stepId) {
  return getOnboardingStep(stepId)?.targetSelector || null;
}
