export const ONBOARDING_VERSION = "v2";

export const ONBOARDING_REQUIRED_STEP_IDS = Object.freeze([
  "welcome",
  "win-condition",
  "spawn-selection",
  "your-district",
  "district-stats",
  "buildings",
  "cash",
  "production",
  "people",
  "heat",
  "day-night",
  "neighbor-districts",
  "spy",
  "robbery",
  "occupy-attack",
  "traps",
  "city-feed",
  "market",
  "alliance",
  "elimination",
  "danger-zone",
  "downtown",
  "next-plan"
]);

const RAW_ONBOARDING_STEPS = Object.freeze([
  Object.freeze({
    id: "welcome",
    title: "Vítej, králi kanálu",
    phase: "Základy",
    badge: "STREET",
    kind: "dirty",
    subtitle: "Město nemá svědomí.",
    body: "Vítej v Empire Streets. Neon svítí, kanál smrdí a každý hajzl tu chce tvoje místo.",
    targetSelector: null,
    placement: "bottom-right",
    completionCondition: "manual",
    fallbackBody: null,
    canSkip: true,
    highlightType: "none",
    optionalActionHint: "Drž hubu a sleduj město. Za chvíli zjistíš, jestli jsi boss, nebo reklama na selhání.",
    detail: "Zapamatuj si: nejsi hrdina. Jsi problém s přístupem k mapě.",
    task: "Vlez dovnitř.",
    taskLabel: "Začni průchod",
    warning: "Město čeká jen na slabé. Nečekej s ním.",
    cta: "Jdu dovnitř"
  }),
  Object.freeze({
    id: "win-condition",
    title: "Koruna pro největšího hajzla",
    phase: "Základy",
    badge: "LOCK",
    kind: "objective",
    subtitle: "Final Lockdown rozhodne, kdo drží krk města.",
    body: "Přežij čistky. Ber území. Do Final Lockdownu musíš přinést nejsilnější impérium.",
    targetSelector: "[data-br-info-open], [data-leaderboard-popup-open]",
    placement: "bottom-right",
    completionCondition: "manual",
    fallbackTitle: "Cíl se neschoval.",
    fallbackBody: "Win condition platí i bez panelu: přežij do Final Lockdownu a zvedej skóre přes území, budovy, zdroje a nízký heat.",
    canSkip: true,
    highlightType: "objective",
    optionalActionHint: "Území pořád bolí soupeře a zvedá skóre. Jen už samo nezavře server.",
    detail: "Zapamatuj si: cash je hezký. Final Lockdown počítá celé impérium.",
    task: "Pochop cíl války.",
    taskLabel: "Najdi cíl hry",
    warning: "Bez mapy máš jen prachy a dobrý důvod brečet."
  }),
  Object.freeze({
    id: "spawn-selection",
    title: "Vyber spawn district",
    phase: "Základy",
    badge: "SPAWN",
    kind: "map",
    subtitle: "První blok rozhodne tempo startu.",
    body: "Pokud server čeká na spawn, vyber dostupný district. Server pak potvrdí tvoji základnu.",
    targetSelector: "[data-feature=\"spawn-selection\"], [data-select-spawn-district-id]",
    placement: "bottom-right",
    completionCondition: "manual",
    fallbackTitle: "Čekám na mapu/server.",
    fallbackBody: "Spawn panel se ukáže, jakmile server pošle aktuální mapu a dostupné startovní distrikty.",
    canSkip: true,
    highlightType: "map",
    optionalActionHint: "Vyber okrajový district, který je označený jako dostupný.",
    detail: "District je tvoje základna. Drž ho, vydělávej a rozšiřuj se ze sousedství.",
    task: "Vyber startovní district.",
    taskLabel: "Vyber spawn",
    targetLabel: "Spawn panel"
  }),
  Object.freeze({
    id: "your-district",
    title: "Tvoje první smradlavá díra",
    phase: "Základy",
    badge: "DISTRICT",
    kind: "map",
    subtitle: "Špinavá díra. Ale tvoje.",
    body: "Tohle je první kus města, který ti ještě neutekl. Klikni na něj, než si tě spletou s turistem.",
    targetSelector: "[data-mount-role=\"map\"], [data-district-canvas], canvas",
    placement: "bottom-right",
    completionCondition: "district:own-opened",
    fallbackTitle: "District zatím mlčí.",
    fallbackBody: "Server zatím neukázal tvůj district. Až ho dostaneš, začne tvůj slavný pád vzhůru.",
    canSkip: true,
    highlightType: "map",
    optionalActionHint: "Klikni na svoje území. Ano, to je ten kus bídy s tvým jménem.",
    detail: "Zapamatuj si: impérium nezačíná proslovem. Začíná kusem bordelu.",
    task: "Klikni na svůj district.",
    taskLabel: "Klikni na území",
    targetLabel: "Tady začíná bordel"
  }),
  Object.freeze({
    id: "district-stats",
    title: "Čísla, ty nešťastníku",
    phase: "Základy",
    badge: "STATS",
    kind: "intel",
    subtitle: "Neon je kulisa. Čísla jsou nůž.",
    body: "District má ownera, zone, heat, influence, budovy a sousedy. Když to nečteš, jen klikáš do průseru.",
    targetSelector: "[data-district-popup-card], [data-district-popup-status], .district-popup-summary-grid",
    placement: "right",
    completionCondition: "district:stats-read",
    fallbackTitle: "Panel districtu není venku.",
    fallbackBody: "Detail districtu teď není dostupný. Owner, zone, heat, influence, budovy a sousedé pořád rozhodují, jestli plánuješ, nebo jen děláš sračky.",
    canSkip: true,
    highlightType: "panel",
    optionalActionHint: "Přečti vlastníka, zone, heat, influence a budovy.",
    detail: "Zapamatuj si: sousedství je seznam lidí, kterým můžeš zítra šlápnout na krk.",
    task: "Zkontroluj statistiky districtu.",
    taskLabel: "Přečti čísla"
  }),
  Object.freeze({
    id: "buildings",
    title: "Budovy nejsou tapeta",
    phase: "Ekonomika",
    badge: "BUILD",
    kind: "money",
    subtitle: "Tohle jsou orgány tvého impéria.",
    body: "Budovy vydělávají, vyrábí, zvedají influence, heat a odemykají akce. Ignoruj je a umřeš elegantně blbě.",
    targetSelector: "[data-district-popup-buildings], [data-district-popup-buildings-list], #buildings-card",
    placement: "right",
    completionCondition: "building:opened",
    fallbackTitle: "Budovy nejsou po ruce.",
    fallbackBody: "Budovy najdeš v detailu districtu nebo přes tlačítko Budovy. Bez nich je impérium jen squat s ambicí.",
    canSkip: true,
    highlightType: "panel",
    optionalActionHint: "Otevři první budovu a zjisti, jestli vydělává, nebo jen zabírá místo.",
    detail: "Zapamatuj si: income, heat, influence, produkce a akce tečou přes budovy.",
    task: "Otevři detail první budovy.",
    taskLabel: "Otevři budovu"
  }),
  Object.freeze({
    id: "cash",
    title: "Prachy: čisté a svinské",
    phase: "Ekonomika",
    badge: "CASH",
    kind: "money",
    subtitle: "Jedny smrdí míň. Druhé koušou víc.",
    body: "Clean cash je nudná, ale drží impérium. Dirty cash je rychlá špína: víc zisku, víc heat, víc do prdele.",
    targetSelector: "[data-topbar-clean-money], [data-topbar-dirty-money], .game-resource-strip",
    placement: "bottom",
    completionCondition: "income:tick",
    fallbackTitle: "Cash lišta je mimo záběr.",
    fallbackBody: "Clean tě drží stabilně. Dirty tě žene rychleji a lepí ti na záda policejní ceduli.",
    canSkip: true,
    highlightType: "resource",
    optionalActionHint: "Počkej na income tick, nebo použij collect, když je dostupný.",
    detail: "Zapamatuj si: laundering a black market jsou dveře. Za jedněmi je zisk, za druhými facka.",
    task: "Zkontroluj cash v horní liště.",
    taskLabel: "Sleduj prachy"
  }),
  Object.freeze({
    id: "production",
    title: "Továrna na špatná rozhodnutí",
    phase: "Ekonomika",
    badge: "CRAFT",
    kind: "money",
    subtitle: "Ikonky? Ne. Munice budoucích průserů.",
    body: "Chemicals, biomass, metal parts, tech core. Palivo pro zbraně, drogy, boosty a špatné nápady se ziskem.",
    targetSelector: "[data-district-building-detail-collect], [data-district-popup-buildings-list], #building-shortcut-grid",
    placement: "right",
    completionCondition: "production:selected",
    fallbackTitle: "Výroba se neukázala.",
    fallbackBody: "Produkční slot teď není dostupný. Pokud district nemá production budovu, tvůj průmyslový plán je zatím báseň bez zubů.",
    canSkip: true,
    highlightType: "panel",
    optionalActionHint: "Vyber nebo seber produkci, pokud to hra dovolí.",
    detail: "Zapamatuj si: storage cap je strop. Plný sklad je promarněný zisk.",
    task: "Najdi production nebo collect.",
    taskLabel: "Zkontroluj výrobu"
  }),
  Object.freeze({
    id: "people",
    title: "Maso s výplatou",
    phase: "Ekonomika",
    badge: "CREW",
    kind: "resource",
    subtitle: "Prachy koupí plán. Lidi ho přežijí.",
    body: "Population a gang members jsou munice s botama. Bez nich posíláš do akce jen ego a to neumí držet district.",
    targetSelector: "[data-gang-members], [data-gang-population], [data-player-gang-members], #profile-gang-card",
    placement: "left",
    completionCondition: "people:read",
    fallbackTitle: "Crew panel není vidět.",
    fallbackBody: "Population nebo gang members panel teď nesvítí. Bez lidí nejsou útoky, obrana ani tvoje velká komedie moci.",
    canSkip: true,
    highlightType: "resource",
    optionalActionHint: "Zkontroluj gang members a population.",
    detail: "Zapamatuj si: každý ztracený člen je tempo v hajzlu.",
    task: "Přečti stav lidí.",
    taskLabel: "Zkontroluj crew"
  }),
  Object.freeze({
    id: "heat",
    title: "Heat: potlesk policie",
    phase: "Riziko",
    badge: "HEAT",
    kind: "danger",
    subtitle: "Policajti taky umí počítat.",
    body: "Heat je smrad po tvém bordelu. Čím víc svinstva pácháš, tím víc modrých parazitů kouká tvým směrem.",
    targetSelector: "[data-gang-heat], .profile-heat-panel",
    placement: "left",
    completionCondition: "heat:opened",
    fallbackTitle: "Heat badge je mimo.",
    fallbackBody: "Heat badge teď není vidět. Vysoký heat mění chytrý plán ve veřejnou sračku.",
    canSkip: true,
    highlightType: "danger",
    optionalActionHint: "Otevři nebo přečti heat badge.",
    detail: "Zapamatuj si: player heat a district heat jsou účtenky za tvoje rozhodnutí.",
    task: "Zkontroluj heat.",
    taskLabel: "Sleduj heat",
    warning: "Heat není dekorace. Je to siréna s odloženou platbou."
  }),
  Object.freeze({
    id: "day-night",
    title: "Den udává, noc krade",
    phase: "Riziko",
    badge: "TIME",
    kind: "system",
    subtitle: "Město má směny. Ty máš následky.",
    body: "Den víc kontroluje. Noc víc krade. Black market, heisty a drby milují tmu, ale tma miluje idioty.",
    targetSelector: ".map-phase-toolbar, [data-game-phase-toggle], [data-map-phase-toggle]",
    placement: "bottom",
    completionCondition: "day-night:opened",
    fallbackTitle: "Časový panel není venku.",
    fallbackBody: "Day/night read model teď není napojený. Překlad: den je kontrola, noc je chaos a šance vydělat průserem.",
    canSkip: true,
    highlightType: "system",
    optionalActionHint: "Sleduj fázi dne. Timing je rozdíl mezi výdělkem a trapnou smrtí.",
    detail: "Zapamatuj si: day/night mění riziko, zisk a kvalitu informací.",
    task: "Zkontroluj fázi dne.",
    taskLabel: "Sleduj čas"
  }),
  Object.freeze({
    id: "neighbor-districts",
    title: "Sousedé: menu dne",
    phase: "Expanze",
    badge: "ADJ",
    kind: "map",
    subtitle: "Nejdeš kam chceš. Jdeš kudy město krvácí.",
    body: "Expanduješ přes sousedy. Slabý soused je oběd. Silný soused je cedule: zkus to a budeš meme.",
    targetSelector: "[data-mount-role=\"map\"], [data-district-canvas], canvas",
    placement: "bottom-right",
    completionCondition: "district:neighbor-opened",
    fallbackTitle: "Soused zatím není označen.",
    fallbackBody: "Sousední district teď není v read modelu. Vyber nejbližší cizí blok a zjisti, jestli jsi lovec, nebo svačina.",
    canSkip: true,
    highlightType: "map",
    optionalActionHint: "Klikni na souseda. Než ho sežere jiný hladový blbec.",
    detail: "Zapamatuj si: bez adjacency je expanze jen hysterické ťukání do mapy.",
    task: "Vyber sousední district.",
    taskLabel: "Vyber souseda",
    targetLabel: "Další kus masa"
  }),
  Object.freeze({
    id: "spy",
    title: "Špehuj, než se ztrapníš",
    phase: "Expanze",
    badge: "SPY",
    kind: "intel",
    subtitle: "Naslepo chodí jen amatér a mrtvola.",
    body: "Spy ukáže obranu, riziko a občas past. Jen blbec kopne do dveří a pak se diví, že uvnitř čeká bolest.",
    targetSelector: "[data-district-action-id=\"spy\"], [data-spy-confirm], [data-district-actions]",
    placement: "right",
    completionCondition: "spy:opened",
    fallbackTitle: "Spy akce není připravená.",
    fallbackBody: "Špehování se ukáže, až bude správný cíl a podmínky. Slepý útok není odvaha. Je to účet za blbost.",
    canSkip: true,
    highlightType: "action",
    optionalActionHint: "Otevři spy na sousední district.",
    detail: "Zapamatuj si: success, partial i fail jsou informace.",
    task: "Otevři spy.",
    taskLabel: "Spusť špehování"
  }),
  Object.freeze({
    id: "robbery",
    title: "Vykrást, ne adoptovat",
    phase: "Expanze",
    badge: "RAID",
    kind: "danger",
    subtitle: "Loot bez převzetí. Rychlé prachy, rychlý průser.",
    body: "Vykradení nebere district. Vpadneš dovnitř, sebereš cash a resources a doufáš, že se crew vrátí celá.",
    targetSelector: "[data-district-action-id=\"rob\"], [data-district-action-id=\"heist\"], [data-robbery-confirm], [data-district-actions]",
    placement: "right",
    completionCondition: "robbery:opened",
    fallbackTitle: "Není vhodný raid cíl.",
    fallbackBody: "Vykradení potřebuje vhodný cíl. Když canRob nesvítí, ber to jako briefing: robbery je loot, ne převzetí districtu.",
    canSkip: true,
    highlightType: "action",
    optionalActionHint: "Otevři vykradení a přečti risk preview.",
    detail: "Zapamatuj si: loot, ztráty a heat. Tři akty malé špinavé tragédie.",
    task: "Otevři vykradení.",
    taskLabel: "Přečti risk preview",
    warning: "Nespouštěj akci bez čtení preview. Tohle není loterie pro klauny."
  }),
  Object.freeze({
    id: "occupy-attack",
    title: "Útok: teď už kradeš mapu",
    phase: "Expanze",
    badge: "ATTACK",
    kind: "danger",
    subtitle: "Tady už nebereš kapsy. Bereš město.",
    body: "Krádež tě nakrmí. Útok tě zvětší. Capture je růst, destroyed je popel a špatné rozhodnutí s ohněm.",
    targetSelector: "[data-district-action-id=\"attack\"], [data-district-action-id=\"occupy\"], [data-district-actions]",
    placement: "right",
    completionCondition: "attack:opened",
    fallbackTitle: "Bojový panel není dostupný.",
    fallbackBody: "Attack nebo occupy se otevře jen u cíle, který dovolí server. Core rozhoduje. Frontend je poslíček se špatnými zprávami.",
    canSkip: true,
    highlightType: "danger",
    optionalActionHint: "Otevři attack nebo occupy panel.",
    detail: "Zapamatuj si: zbraně, obrana, pasti a cooldowny se počítají.",
    task: "Otevři bojový panel.",
    taskLabel: "Připrav útok",
    warning: "Útok bez plánu je jen drahá sebevražda s UI."
  }),
  Object.freeze({
    id: "traps",
    title: "Pasti: komedie bolesti",
    phase: "Expanze",
    badge: "TRAP",
    kind: "danger",
    subtitle: "Tiché svinstvo pro hlasité idioty.",
    body: "Past čeká v districtu, až někdo přijde hrát hrdinu. Pak přijde bum, pláč a ticho po cizím egu.",
    targetSelector: "[data-district-action-id=\"trap\"], [data-district-actions]",
    placement: "right",
    completionCondition: "trap:opened",
    fallbackTitle: "Trap akce není venku.",
    fallbackBody: "Trap akce teď není dostupná. Past trestá lidi, kteří si myslí, že dveře jsou pozvánka.",
    canSkip: true,
    highlightType: "danger",
    optionalActionHint: "Najdi toxic trap v akcích districtu.",
    detail: "Zapamatuj si: dobrá past nemluví. Nechá mluvit škody.",
    task: "Zkontroluj past.",
    taskLabel: "Najdi trap"
  }),
  Object.freeze({
    id: "city-feed",
    title: "Drby z kanálu",
    phase: "Intel",
    badge: "FEED",
    kind: "intel",
    subtitle: "Město lže. Občas užitečně.",
    body: "City feed míchá potvrzené události a drby. Ignoruj ho a budeš poslední, kdo zjistí, proč hoříš.",
    targetSelector: "[data-building-action-feed], [data-district-popup-gossip], [data-district-popup-gossip-list]",
    placement: "left",
    completionCondition: "city-feed:opened",
    fallbackTitle: "Feed teď drží hubu.",
    fallbackBody: "Až se otevře, rozliš confirmed events, rumors a truthiness. Město lže, ale někdy lže směrem k pravdě.",
    canSkip: true,
    highlightType: "intel",
    optionalActionHint: "Přečti poslední události nebo drby.",
    detail: "Zapamatuj si: feed je intel z kanálu. Smrdí, ale někdy zachrání krk.",
    task: "Zkontroluj city feed.",
    taskLabel: "Čti město"
  }),
  Object.freeze({
    id: "market",
    title: "Bazar zoufalých géniů",
    phase: "Intel",
    badge: "MARKET",
    kind: "money",
    subtitle: "Zoufalí kupují. Chytří prodávají.",
    body: "Market je místo, kde se panika mění na marži. Black market je špinavější, dražší a občas přesně to, co potřebuješ.",
    targetSelector: "[data-market-popup-open], [data-market-popup], #market-card",
    placement: "left",
    completionCondition: "market:opened",
    fallbackTitle: "Market zatím není připravený.",
    fallbackBody: "Market UI teď není dostupné. Krok zůstává informační: normal market, black market risk, listings a ceny, co skáčou jak opilý prorok.",
    canSkip: true,
    highlightType: "resource",
    optionalActionHint: "Otevři bazar.",
    detail: "Zapamatuj si: scarce resources jsou zbraň. Prodej ve správný čas je tichá loupež.",
    task: "Otevři market.",
    taskLabel: "Otevři bazar"
  }),
  Object.freeze({
    id: "alliance",
    title: "Aliance: přátelé s noži",
    phase: "Intel",
    badge: "ALLY",
    kind: "system",
    subtitle: "Rodina? Ne. Dočasná smlouva s nožem.",
    body: "Aliance dá štít, tlak a větší skóre do Final Lockdownu. Ale není to rodina. Jen lidi, kterým se zatím hodíš živý.",
    targetSelector: "[data-alliance-popup-open], #alliance-btn, [data-gang-alliance]",
    placement: "left",
    completionCondition: "alliance:opened",
    fallbackTitle: "Aliance není po ruce.",
    fallbackBody: "Alliance UI teď není dostupné. Aliance ti může pomoct přežít a nabrat skóre do Final Lockdownu, ale tvoji osobní slabost nevypere.",
    canSkip: true,
    highlightType: "system",
    optionalActionHint: "Otevři aliance nebo profil gangu.",
    detail: "Zapamatuj si: alliance control je moc. Slabý člen je pořád problém s logem.",
    task: "Zkontroluj alianci.",
    taskLabel: "Zkontroluj alianci"
  }),
  Object.freeze({
    id: "elimination",
    title: "Čistka, ó radosti",
    phase: "Endgame",
    badge: "PURGE",
    kind: "danger",
    subtitle: "Slabí mizí. Město ani nemrkne.",
    body: "První čistka po 8h. Pak každé 4h. Mezi 00:00 a 06:00 se nevyhazuje, protože i kat má pauzu.",
    targetSelector: "[data-br-info-open], #battle-royale-info-modal",
    placement: "bottom",
    completionCondition: "elimination:opened",
    fallbackTitle: "Eliminace zatím bez panelu.",
    fallbackBody: "Elimination read model teď nesvítí. Pravidlo je pořád stejné: slabí mizí. Defeated znamená, že server zabouchl víko.",
    canSkip: true,
    highlightType: "danger",
    optionalActionHint: "Zkontroluj Battle Royale info a další eliminaci.",
    detail: "Zapamatuj si: posledních 8 dohraje finále. Do té doby je čas kat s hodinkami.",
    task: "Přečti eliminační stav.",
    taskLabel: "Najdi čistku",
    warning: "Být poslední není drama. Je to odchod."
  }),
  Object.freeze({
    id: "danger-zone",
    title: "Danger zone, ne wellness",
    phase: "Endgame",
    badge: "DANGER",
    kind: "danger",
    subtitle: "Jestli svítíš červeně, něco smrdí. Ty.",
    body: "V danger zone nebreč. Získej district, zvedni influence, posil budovy a přestaň být snadný oběd.",
    targetSelector: "[data-br-info-open], #battle-royale-info-modal, [data-leaderboard-popup-open]",
    placement: "bottom",
    completionCondition: "danger-zone:opened",
    fallbackTitle: "Risk panel není venku.",
    fallbackBody: "Danger zone data teď nejsou dostupná. Území je hlavní váha; influence, buildings a resources pomáhají. Cash bez mapy je pozlacená sračka.",
    canSkip: true,
    highlightType: "danger",
    optionalActionHint: "Najdi svůj risk: safe, danger nebo critical.",
    detail: "Zapamatuj si: aliance pomůže. Slabý hráč je ale pořád katastrofa s doprovodem.",
    task: "Zkontroluj svůj risk.",
    taskLabel: "Najdi svůj risk",
    warning: "Safe je plán. Critical je město, jak si brousí zuby."
  }),
  Object.freeze({
    id: "downtown",
    title: "Downtown: drahá past",
    phase: "Endgame",
    badge: "DOWNTOWN",
    kind: "objective",
    subtitle: "Drahé baráky, drahé následky.",
    body: "Burza, Magistrát, Soud, Letiště, Banka. Tohle nejsou památky. Jsou to páky, co lámou server.",
    targetSelector: "[data-mount-role=\"map\"], #building-shortcut-grid, #buildings-card",
    placement: "bottom-right",
    completionCondition: "downtown:read",
    fallbackTitle: "Downtown není v záběru.",
    fallbackBody: "Vzácné budovy teď nejsou vidět. Až je najdeš, nechovej se k nim jako k obyčejným barákům.",
    canSkip: true,
    highlightType: "map",
    optionalActionHint: "Hledej Downtown a high-value building sety.",
    detail: "Zapamatuj si: court, city hall, stock exchange, central bank, airport, port a VIP lounge mění tlak na celý server.",
    task: "Najdi high-value cíl.",
    taskLabel: "Hledej páky"
  }),
  Object.freeze({
    id: "next-plan",
    title: "A teď nebuď tragéd",
    phase: "Endgame",
    badge: "PLAN",
    kind: "objective",
    subtitle: "Dost keců. Teď přežij.",
    body: "Drž district. Sbírej income. Hlídej heat. Špehuj sousedy. Ber slabé cíle. Nelez do danger zone jak opilý král popelnice.",
    targetSelector: "[data-mount-role=\"map\"], #game-root",
    placement: "bottom-right",
    completionCondition: "manual",
    fallbackTitle: "Mapa zrovna mlčí.",
    fallbackBody: "Plán zůstává: district, income, heat, soused, rozhodnutí, eliminace. Ano, je to práce. I tragédie má administrativu.",
    canSkip: true,
    highlightType: "objective",
    optionalActionHint: "Klikni vlastní district, zkontroluj budovy, seber produkci, sleduj heat, najdi souseda a rozhodni: spy, vykrást, nebo útočit.",
    detail: "Checklist: území, budovy, produkce, heat, soused, akce, eliminace, útěk z danger zone.",
    task: "Jdi pro město.",
    taskLabel: "Dokonči briefing",
    warning: "Město nečeká na tvůj charakterový vývoj.",
    cta: "Jdu pro město"
  })
]);

const FIRST_PLAYER_ONBOARDING_COPY = Object.freeze({
  welcome: Object.freeze({
    title: "Vítej v Empire Streets",
    subtitle: "Ulice drží ten, kdo čte mapu.",
    body: "Clean cash drží provoz, dirty cash vydělá rychle, influence otevírá tahy a heat je stopa pro policii.",
    optionalActionHint: "Projdi krátký briefing. Každý krok je jen UI guidance, výsledky dál potvrzuje server.",
    detail: "Začni malým district, sleduj zdroje a nespouštěj risk akce naslepo.",
    task: "Pochop základní zdroje.",
    taskLabel: "Start briefing",
    warning: "Tutorial nic nemění ve hře. Jen ukazuje, kam kliknout.",
    cta: "Pokračovat"
  }),
  "win-condition": Object.freeze({
    title: "Cíl Free alpha",
    subtitle: "Přežít, růst a zůstat relevantní.",
    body: "Ve Free režimu rozhoduje impérium: distrikty, budovy, zdroje, vliv a schopnost přežít Final Lockdown.",
    fallbackBody: "Cíl platí i bez panelu: drž území, zvyšuj skóre a nenech heat zničit tempo.",
    optionalActionHint: "Otevři Battle Royale info nebo leaderboard, pokud je panel dostupný.",
    detail: "Cash pomáhá, ale město počítá celé impérium.",
    task: "Zkontroluj cíl serveru.",
    taskLabel: "Cíl hry",
    warning: "Nejslabší hráči postupně mizí z mapy."
  }),
  "spawn-selection": Object.freeze({
    title: "Vyber spawn district",
    subtitle: "První blok je tvoje základna.",
    body: "Pokud server čeká na spawn, vyber dostupný district. Server pak potvrdí tvoji home oblast.",
    fallbackBody: "Čekám na mapu/server. Spawn panel se ukáže, jakmile je dostupný autoritativní stav.",
    optionalActionHint: "Vyber dostupný okrajový district.",
    detail: "District je tvoje základna. Drž ho, vydělávej a rozšiřuj se ze sousedství.",
    task: "Vyber startovní district.",
    taskLabel: "Spawn"
  }),
  "your-district": Object.freeze({
    title: "Klikni na svůj district",
    subtitle: "Tady začíná tvoje impérium.",
    body: "Po spawnu klikni na vlastní district a otevři detail. Uvidíš příjem, heat, obranu, budovy a sousedy.",
    fallbackBody: "Server zatím neposlal home district. Jakmile dorazí mapa, pokračuj vlastním blokem.",
    optionalActionHint: "Klikni na svůj označený district.",
    detail: "Vlastní district je místo, odkud plánuješ první expanzi.",
    task: "Otevři svůj district.",
    taskLabel: "Vlastní district",
    targetLabel: "Tvoje území"
  }),
  "district-stats": Object.freeze({
    title: "Přečti čísla districtu",
    subtitle: "Bez informací je každý tah drahý.",
    body: "Sleduj ownera, typ zóny, příjem, heat, vliv, budovy a sousedy. Tyhle hodnoty určují další bezpečný krok.",
    fallbackBody: "Detail districtu teď není dostupný. Jakmile ho otevřeš, začni ownerem, heatem a sousedy.",
    optionalActionHint: "Přečti ownera, zone, heat, influence a budovy.",
    detail: "Sousedé jsou první možné cíle, ale server rozhoduje, které akce jsou enabled.",
    task: "Zkontroluj statistiky.",
    taskLabel: "Intel"
  }),
  buildings: Object.freeze({
    title: "Najdi budovy",
    subtitle: "Budovy drží ekonomiku při životě.",
    body: "Budovy dávají income, produkci, vliv, obranu nebo nové akce. Začni tím, co už má vlastní district.",
    fallbackBody: "Budovy se ukážou v detailu districtu nebo v panelu Budovy.",
    optionalActionHint: "Otevři první dostupnou budovu.",
    detail: "Income, heat a produkce tečou přes autoritativní model, ne přes UI.",
    task: "Otevři budovu.",
    taskLabel: "Budovy"
  }),
  cash: Object.freeze({
    title: "Sleduj cash",
    subtitle: "Čisté drží provoz, špinavé zrychluje start.",
    body: "Clean cash je stabilní rozpočet. Dirty cash roste rychleji, ale může zvedat heat a policejní tlak.",
    fallbackBody: "Cash lišta není vidět, ale pravidlo platí: rychlý zisk často nechává stopu.",
    optionalActionHint: "Počkej na income tick nebo použij dostupný collect.",
    detail: "Dirty cash vydělá rychle, ale policie si toho všimne.",
    task: "Zkontroluj peníze.",
    taskLabel: "Cash"
  }),
  production: Object.freeze({
    title: "Najdi první produkci",
    subtitle: "Materiál je tempo do dalších tahů.",
    body: "Chemicals, biomass, metal parts a tech core krmí budovy, výbavu a silnější akce.",
    fallbackBody: "Produkční slot teď nemusí být dostupný. Pokud ho nemáš, pokračuj přes income a sousedy.",
    optionalActionHint: "Vyber nebo seber produkci, pokud je akce enabled.",
    detail: "Plný sklad je promarněný tick.",
    task: "Zkontroluj produkci.",
    taskLabel: "Produkce"
  }),
  people: Object.freeze({
    title: "Zkontroluj lidi",
    subtitle: "Bez lidí neudržíš ulici.",
    body: "Population a gang members určují, co zvládneš obsadit, bránit nebo riskovat.",
    fallbackBody: "Crew panel není vidět. Vrať se k němu před agresivní akcí.",
    optionalActionHint: "Zkontroluj gang members a population.",
    detail: "Každý ztracený člen zpomaluje další tahy.",
    task: "Přečti stav lidí.",
    taskLabel: "Crew"
  }),
  heat: Object.freeze({
    title: "Pozor na heat",
    subtitle: "Heat je stopa, kterou po sobě necháš.",
    body: "Agresivní akce, dirty cash a risk produkce zvyšují policejní tlak. Vysoký heat umí zlomit tempo.",
    fallbackBody: "Heat badge není vidět. Sleduj ho před každou risk akcí.",
    optionalActionHint: "Otevři nebo přečti heat badge.",
    detail: "Heat není dekorace. Je to varování před zásahem.",
    task: "Zkontroluj heat.",
    taskLabel: "Heat",
    warning: "Když heat roste rychleji než impérium, zpomal."
  }),
  "day-night": Object.freeze({
    title: "Sleduj čas města",
    subtitle: "Den a noc mění rytmus rizika.",
    body: "Některé tahy dávají jiný smysl podle fáze města. Čas je součást strategie.",
    fallbackBody: "Časový panel teď není vidět. Pokračuj a sleduj ho, až se zobrazí.",
    optionalActionHint: "Zkontroluj fázi dne.",
    detail: "Timing rozhoduje, kdy sbírat, špehovat nebo tlačit na sousedy.",
    task: "Zkontroluj fázi.",
    taskLabel: "Čas"
  }),
  "neighbor-districts": Object.freeze({
    title: "Najdi souseda",
    subtitle: "Expanze začíná vedle tebe.",
    body: "Klikni na sousední district a zjisti, jestli je prázdný, cizí, bráněný nebo vhodný pro intel.",
    fallbackBody: "Soused zatím není označený. Jakmile mapa reaguje, vyber blok vedle svého districtu.",
    optionalActionHint: "Klikni na sousední district.",
    detail: "Bez adjacency není expanze plán, jen klikání.",
    task: "Vyber souseda.",
    taskLabel: "Soused",
    targetLabel: "Další cíl"
  }),
  spy: Object.freeze({
    title: "Pošli špeha",
    subtitle: "Pošli špeha, než pošleš lidi.",
    body: "Spy je první bezpečný krok před útokem. Ukáže obranu, riziko a někdy i pasti.",
    fallbackBody: "Spy akce se ukáže, až server povolí vhodný cíl a podmínky.",
    optionalActionHint: "Otevři spy na sousední district, pokud je enabled.",
    detail: "Úspěch, partial i fail jsou informace. Nepředstírej jistotu.",
    task: "Otevři spy.",
    taskLabel: "Spy"
  }),
  robbery: Object.freeze({
    title: "Vykradení je loot",
    subtitle: "Rychlý zisk, větší stopa.",
    body: "Robbery nebere district. Bere cash a materiál, ale může stát lidi a heat.",
    fallbackBody: "Vykradení potřebuje vhodný cíl. Pokud není enabled, zůstaň u intel a income.",
    optionalActionHint: "Otevři robbery preview, pokud je dostupné.",
    detail: "Čti risk preview před potvrzením.",
    task: "Přečti robbery preview.",
    taskLabel: "Robbery",
    warning: "Nespouštěj risk akci bez preview."
  }),
  "occupy-attack": Object.freeze({
    title: "Útok bere mapu",
    subtitle: "Tady už nejde jen o loot.",
    body: "Attack nebo occupy mění držení districtu jen tehdy, když server akci povolí a command projde.",
    fallbackBody: "Bojový panel se otevře jen u cíle, který dovolí server.",
    optionalActionHint: "Otevři attack nebo occupy, pokud je enabled.",
    detail: "Zbraně, obrana, pasti a cooldowny se počítají na serveru.",
    task: "Přečti bojový panel.",
    taskLabel: "Útok",
    warning: "Útok bez intel je drahý hazard."
  }),
  traps: Object.freeze({
    title: "Pasti brání hranice",
    subtitle: "Tichá obrana trestá první chybu.",
    body: "Past čeká na cizí akci v districtu. Používej ji na místech, která chceš opravdu držet.",
    fallbackBody: "Trap akce teď není dostupná. Vrať se k ní, až ji server nabídne.",
    optionalActionHint: "Najdi trap v akcích districtu.",
    detail: "Pasti jsou obrana, ne náhrada plánu.",
    task: "Zkontroluj past.",
    taskLabel: "Pasti"
  }),
  "city-feed": Object.freeze({
    title: "Čti city feed",
    subtitle: "Město mluví v signálech.",
    body: "Feed míchá události, drby a varování. Ne všechno je jisté, ale ignorovat ho je chyba.",
    fallbackBody: "Feed teď není dostupný. Sleduj ho, až se otevře v districtu nebo panelu.",
    optionalActionHint: "Přečti poslední události nebo drby.",
    detail: "Přesnou pravdu potvrdí špeh, akce nebo riziko.",
    task: "Zkontroluj feed.",
    taskLabel: "Feed"
  }),
  market: Object.freeze({
    title: "Market je volitelný",
    subtitle: "Zdroje mají cenu, když chybí.",
    body: "Market a black market pomůžou, když potřebuješ materiál nebo chceš prodat přebytek.",
    fallbackBody: "Market UI teď nemusí být dostupné. Není nutný pro první tah.",
    optionalActionHint: "Otevři market, pokud je dostupný.",
    detail: "Nakupuj jen to, co podporuje další konkrétní krok.",
    task: "Zkontroluj market.",
    taskLabel: "Market"
  }),
  alliance: Object.freeze({
    title: "Aliance jsou pozdější vrstva",
    subtitle: "Síla, ochrana i riziko dohody.",
    body: "Aliance může pomoci přežít tlak, ale první minuty zvládneš přes district, income a intel.",
    fallbackBody: "Alliance UI teď není dostupné. Vrať se k němu po prvních tazích.",
    optionalActionHint: "Otevři aliance nebo profil gangu.",
    detail: "Důvěra je výhoda jen do chvíle, kdy se vyplatí zrada.",
    task: "Zkontroluj alianci.",
    taskLabel: "Aliance"
  }),
  elimination: Object.freeze({
    title: "Sleduj eliminace",
    subtitle: "Slabí postupně mizí.",
    body: "Battle Royale tlak řeší, kdo přežije do pozdější fáze. Nezůstávej dlouho dole.",
    fallbackBody: "Elimination panel teď není vidět. Pravidlo zůstává: drž tempo a skóre.",
    optionalActionHint: "Otevři Battle Royale info.",
    detail: "Poslední fáze zvýhodní stabilní impérium, ne náhodný klik.",
    task: "Přečti eliminační stav.",
    taskLabel: "Eliminace",
    warning: "Danger zone není kosmetika."
  }),
  "danger-zone": Object.freeze({
    title: "Nezůstávej v danger zone",
    subtitle: "Nízké skóre je varování.",
    body: "Když jsi v danger zone, získej district, posil income, drž aktivitu a sniž zbytečný heat.",
    fallbackBody: "Risk data teď nejsou dostupná. Plán je stejný: území, income, intel, další tah.",
    optionalActionHint: "Najdi svůj risk v Battle Royale info nebo leaderboardu.",
    detail: "Safe znamená tempo. Critical znamená, že musíš rychle změnit plán.",
    task: "Zkontroluj risk.",
    taskLabel: "Risk",
    warning: "Když svítíš dole, hraj jednoduše a bezpečně."
  }),
  downtown: Object.freeze({
    title: "Downtown je pozdější cíl",
    subtitle: "Velké páky, velké riziko.",
    body: "Downtown budovy mění tlak na serveru, ale první kroky patří základně, sousedům a income.",
    fallbackBody: "Downtown nemusí být v záběru. Stačí vědět, že nejde o běžný district.",
    optionalActionHint: "Hledej Downtown a high-value budovy, až budeš stabilní.",
    detail: "Banky, soudy a letiště jsou strategické páky pro pozdější fázi.",
    task: "Zapamatuj si high-value cíle.",
    taskLabel: "Downtown"
  }),
  "next-plan": Object.freeze({
    title: "Další plán",
    subtitle: "Teď hraj první smysluplný cyklus.",
    body: "Drž district. Seber income. Hlídej heat. Pošli špeha na souseda. Pak teprve zvaž robbery, occupy nebo útok.",
    fallbackBody: "Mapa teď mlčí. Plán zůstává: district, income, heat, soused, enabled akce.",
    optionalActionHint: "Klikni vlastní district, zkontroluj budovy, seber produkci, sleduj heat a najdi souseda.",
    detail: "Checklist: území, budovy, produkce, heat, špeh, další tah.",
    task: "Začni první cyklus.",
    taskLabel: "Dokončit briefing",
    warning: "Server vždy potvrzuje, co se opravdu stalo.",
    cta: "Jdu hrát"
  })
});

export const ONBOARDING_STEPS = Object.freeze(RAW_ONBOARDING_STEPS.map((step) =>
  Object.freeze({
    ...step,
    ...(FIRST_PLAYER_ONBOARDING_COPY[step.id] || {})
  })
));

export function getOnboardingStep(stepId) {
  return ONBOARDING_STEPS.find((step) => step.id === stepId) || null;
}

export function getOnboardingStepIndex(stepId) {
  const index = ONBOARDING_STEPS.findIndex((step) => step.id === stepId);
  return index >= 0 ? index : 0;
}

export function getOnboardingTargetSelector(stepId) {
  return getOnboardingStep(stepId)?.targetSelector || null;
}
