import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const root = process.cwd();
const readText = (path) => readFileSync(resolve(root, path), "utf8").replace(/\r\n/g, "\n");

describe("onboarding district popup layer", () => {
  it("keeps District 2 popup above onboarding and removes phone backdrop dimming", () => {
    const onboardingCss = readText("page-assets/css/styles-onboarding.css");
    const runtimeSource = readText("page-assets/js/app/runtime.js");
    const allianceRuntimeSource = readText("page-assets/js/app/alliance-runtime.js");

    expect(runtimeSource).toContain("popup.dataset.districtId = String(district.id);");
    expect(runtimeSource).toContain("popupCard.dataset.districtId = String(district.id);");
    expect(runtimeSource).toContain("const ONBOARDING_ATTACK_TARGET_DISTRICT_ID = 1;");
    expect(runtimeSource).toContain("function isOnboardingDistrictClickAllowed(district, documentRef = document)");
    expect(runtimeSource).toContain('if (activeStepId === "spy")');
    expect(runtimeSource).toContain('if (activeStepId === "attack-order")');
    expect(runtimeSource).toContain("return Number(district?.id || 0) === ONBOARDING_SPY_TARGET_DISTRICT_ID;");
    expect(runtimeSource).toContain("return Number(district?.id || 0) === ONBOARDING_ATTACK_TARGET_DISTRICT_ID;");
    expect(runtimeSource).toContain("if (!isOnboardingDistrictClickAllowed(district, root?.ownerDocument || document))");
    expect(runtimeSource).toContain("function resetOnboardingTrapTargetState(root = getDefaultRuntimeRoot())");
    expect(runtimeSource).toContain("const ownedDistrictIds = [ONBOARDING_ATTACK_TARGET_DISTRICT_ID];");
    expect(runtimeSource).toContain("delete nextPoliceActionById[ONBOARDING_ATTACK_TARGET_DISTRICT_ID];");
    expect(runtimeSource).toContain("districtId !== ONBOARDING_ATTACK_TARGET_DISTRICT_ID");
    expect(runtimeSource).toContain("function isOnboardingDistrictPopupTopLayerTarget(district, documentRef = document)");
    expect(runtimeSource).toContain("function ensureOnboardingDistrictPopupTopLayer(popupElement, district, documentRef = document)");
    expect(runtimeSource).toContain("body.append(popupElement);");
    expect(runtimeSource).toContain("ensureOnboardingDistrictPopupTopLayer(popup, district, root?.ownerDocument || document);");
    expect(runtimeSource).not.toContain("nextTrapById[ONBOARDING_SPY_TARGET_DISTRICT_ID] = {");
    expect(runtimeSource).not.toContain("nextTrapById[ONBOARDING_SPY_TARGET_DISTRICT_ID] || {}");
    expect(runtimeSource).toContain("delete nextTrapById[districtId];");
    expect(runtimeSource).toContain("function getOnboardingDistrictActionHint(district, documentRef = document)");
    expect(runtimeSource).toContain('actionId: "spy"');
    expect(runtimeSource).toContain('label: "Špehovat"');
    expect(runtimeSource).toContain("function applyOnboardingDistrictActionHint(district, elements = {}, documentRef = document)");
    expect(runtimeSource).toContain("button.dataset.onboardingActionHint = \"true\";");
    expect(runtimeSource).toContain("function ensureOnboardingActionConfirmTopLayer(confirmPopupElement, actionId, district, documentRef = document)");
    expect(runtimeSource).toContain("confirmPopupElement.dataset.onboardingActionConfirmLayer = String(actionId || \"\");");
    expect(runtimeSource).toContain('ensureOnboardingActionConfirmTopLayer(trapConfirmPopup, "trap", selectedDistrict, root?.ownerDocument || document);');
    expect(runtimeSource).toContain('ensureOnboardingActionConfirmTopLayer(spyConfirmPopup, "spy", selectedDistrict, root?.ownerDocument || document);');
    expect(runtimeSource).toContain('type: currentTrapDistrictId && currentTrapDistrictId !== selectedDistrict.id ? "trap:moved" : "trap:armed"');
    expect(runtimeSource).toContain("createOnboardingSandboxSession(getPersistedAuthoritySession()");
    expect(runtimeSource).toContain("function startOnboardingSandbox(root = getDefaultRuntimeRoot())");
    expect(runtimeSource).toContain("function stopOnboardingSandbox(root = getDefaultRuntimeRoot())");
    expect(runtimeSource).toContain('document.dispatchEvent(new CustomEvent("empire:onboarding-alliance-reset"');
    expect(runtimeSource).toContain("onStart: () => startOnboardingSandbox(root)");
    expect(runtimeSource).toContain("onComplete: () => stopOnboardingSandbox(root)");
    expect(runtimeSource).not.toContain("DEV_ONLY_ONBOARDING_START_STATE");
    expect(runtimeSource).not.toContain("devOnlyOnboardingStartPending");
    expect(allianceRuntimeSource).toContain("const isOnboardingActiveForAllianceDemo = () =>");
    expect(allianceRuntimeSource).toContain("const suppressLocalDemoAlliance = isOnboardingActiveForAllianceDemo();");
    expect(allianceRuntimeSource).toContain("const shouldUseActiveDemoAlliance = !suppressLocalDemoAlliance && getCurrentGamePhaseForAllianceDemo() === \"launch\";");
    expect(allianceRuntimeSource).toContain('document.addEventListener("empire:onboarding-alliance-reset"');
    expect(onboardingCss).toContain('html[data-onboarding-step="spy"] body.game-body .district-popup-shell[data-district-id="2"]:not([hidden])');
    expect(onboardingCss).toContain('html[data-onboarding-step="attack-order"] body.game-body .district-popup-shell[data-district-id="1"]:not([hidden])');
    expect(onboardingCss).toContain('.district-popup-action[data-district-action-id="spy"][data-onboarding-action-hint="true"]');
    expect(onboardingCss).toContain('.district-popup-action[data-district-action-id="trap"][data-onboarding-action-hint="true"]');
    expect(onboardingCss).toContain('.district-popup-action[data-district-action-id="trap"][data-onboarding-trap-move-hint="true"]');
    expect(onboardingCss).toContain("animation: onboardingTargetPulse 1.15s ease-in-out infinite;");
    expect(onboardingCss).toContain("isolation: isolate;");
    expect(onboardingCss).toContain("z-index: 13000 !important;");
    expect(onboardingCss).toContain("z-index: 26000 !important;");
    expect(onboardingCss).toContain('#spy-confirm-modal[data-onboarding-action-confirm-layer="spy"]:not(.hidden):not([hidden])');
    expect(onboardingCss).toContain('#trap-confirm-modal[data-onboarding-action-confirm-layer="trap"]:not(.hidden):not([hidden])');
    expect(onboardingCss).toContain("z-index: var(--empire-z-action-confirmation) !important;");
    expect(onboardingCss).toContain("--onboarding-trap-confirm-top: max(104px, calc(var(--desktop-topbar-offset, 76px) + 28px));");
    expect(onboardingCss).toContain("place-items: start center !important;");
    expect(onboardingCss).toContain("padding: var(--onboarding-trap-confirm-top) 18px 18px !important;");
    expect(onboardingCss).toContain("--onboarding-trap-confirm-top: max(118px, calc(var(--mobile-topbar-offset, 72px) + 34px));");
    expect(onboardingCss).toContain("max-height: calc(var(--mobile-locked-vh, 100dvh) - var(--onboarding-trap-confirm-top) - max(14px, env(safe-area-inset-bottom))) !important;");
    expect(onboardingCss).toContain('.district-popup-card[data-district-id="2"]');
    expect(onboardingCss).toContain("position: relative;");
    expect(onboardingCss).toContain("z-index: 13010 !important;");
    expect(onboardingCss).toContain('html[data-onboarding-step="spy"]:has(body.game-body .district-popup-shell[data-district-id="2"]:not([hidden])) .empire-onboarding-backdrop');
    expect(onboardingCss).toContain('html[data-onboarding-step="spy"]:has(body.game-body .district-popup-shell[data-district-id="2"]:not([hidden])) .empire-onboarding-backdrop__mask');
    expect(onboardingCss).toContain("opacity: 0 !important;");
  });
});
