export const FACTION_WEAPON_PRESETS = {
  mafian: { "baseball-bat": 2, pistol: 12, grenade: 1, smg: 0, bazooka: 0, vest: 1, barricades: 2, cameras: 1, "defense-tower": 0, alarm: 1 },
  kartel: { "baseball-bat": 1, pistol: 10, grenade: 2, smg: 3, bazooka: 0, vest: 0, barricades: 1, cameras: 1, "defense-tower": 0, alarm: 0 },
  kult: { "baseball-bat": 18, pistol: 8, grenade: 0, smg: 0, bazooka: 0, vest: 1, barricades: 1, cameras: 0, "defense-tower": 0, alarm: 0 },
  "tajna-organizace": { "baseball-bat": 0, pistol: 9, grenade: 1, smg: 1, bazooka: 0, vest: 1, barricades: 0, cameras: 3, "defense-tower": 0, alarm: 2 },
  hackeri: { "baseball-bat": 0, pistol: 6, grenade: 0, smg: 0, bazooka: 0, vest: 0, barricades: 0, cameras: 4, "defense-tower": 0, alarm: 3 },
  "motorkarsky-gang": { "baseball-bat": 5, pistol: 14, grenade: 2, smg: 1, bazooka: 0, vest: 1, barricades: 1, cameras: 0, "defense-tower": 0, alarm: 0 },
  "soukroma-armada": { "baseball-bat": 1, pistol: 16, grenade: 2, smg: 4, bazooka: 1, vest: 4, barricades: 3, cameras: 2, "defense-tower": 1, alarm: 2 },
  korporace: { "baseball-bat": 0, pistol: 8, grenade: 0, smg: 0, bazooka: 0, vest: 2, barricades: 1, cameras: 3, "defense-tower": 0, alarm: 4 }
};

export const FACTION_CATALOG = {
  mafian: { id: "mafian", name: "Mafián", tagline: "Stará škola vydírání a vlivu.", description: "Silný ekonomický start, tlak na ochranu a kontrolu lokálního trhu.", startingPackage: { cleanMoney: 140000, dirtyMoney: 60000, influence: 220, heat: 30 }, advantages: ["Vyšší čistý kapitál", "Lepší income z legálních krytí", "Nižší heat decay penalizace"], disadvantages: ["Pomalejší expanze do street výroby", "Slabší kyber obrana"] },
  kartel: { id: "kartel", name: "Kartel", tagline: "Výroba, logistika a tvrdé cashflow.", description: "Rychlý dirty-money start a silný tlak na produkci a distribuci.", startingPackage: { cleanMoney: 70000, dirtyMoney: 135000, influence: 180, heat: 55 }, advantages: ["Vyšší špinavé peníze", "Levnější produkce", "Silnější drug lab start"], disadvantages: ["Vyšší základní heat", "Slabší alliance důvěra"] },
  kult: { id: "kult", name: "Kult", tagline: "Fanatická disciplína a tichý nátlak.", description: "Vyšší pasivní vliv a lepší kontrola efektů, ale slabší ekonomika.", startingPackage: { cleanMoney: 50000, dirtyMoney: 45000, influence: 320, heat: 20 }, advantages: ["Vyšší startovní vliv", "Silnější efektové bonusy", "Nižší upkeep členů"], disadvantages: ["Méně peněz", "Slabší palebná síla na startu"] },
  "tajna-organizace": { id: "tajna-organizace", name: "Tajná organizace", tagline: "Skrytá síť kontaktů a infiltrace.", description: "Silná infiltrace a nižší viditelnost, ale pomalejší otevřená produkce.", startingPackage: { cleanMoney: 80000, dirtyMoney: 70000, influence: 160, heat: 10 }, advantages: ["Nižší heat generace", "Silnější spy utility", "Lepší informační kontrola"], disadvantages: ["Méně veřejného vlivu", "Pomalejší industriální růst"] },
  hackeri: { id: "hackeri", name: "Hackeři", tagline: "Data, sabotáže a asymetrická válka.", description: "Výborná kontrola informací a rychlý technologický start.", startingPackage: { cleanMoney: 65000, dirtyMoney: 50000, influence: 240, heat: 18 }, advantages: ["Silnější digitální utility", "Vyšší bonus na průzkum", "Rychlejší event reakce"], disadvantages: ["Slabší fyzická obrana", "Nižší startovní výzbroj"] },
  "motorkarsky-gang": { id: "motorkarsky-gang", name: "Motorkářský gang", tagline: "Mobilita, nájezdy a rychlý tlak.", description: "Agresivní start s dobrým raid tlakem a mobilitou.", startingPackage: { cleanMoney: 60000, dirtyMoney: 80000, influence: 140, heat: 45 }, advantages: ["Vyšší raid tempo", "Lepší mobilita", "Silný early combat"], disadvantages: ["Horší ekonomická stabilita", "Vyšší ztráty při delším konfliktu"] },
  "soukroma-armada": { id: "soukroma-armada", name: "Soukromá armáda", tagline: "Disciplína, výzbroj a tvrdá kontrola.", description: "Nejlepší bojový start a obrana, vykoupené vyšší cenou a heatem.", startingPackage: { cleanMoney: 90000, dirtyMoney: 50000, influence: 170, heat: 60 }, advantages: ["Silná výzbroj", "Vyšší obrana districtů", "Lepší raid protection"], disadvantages: ["Vysoký upkeep", "Vyšší viditelnost pro policii"] },
  korporace: { id: "korporace", name: "Korporace", tagline: "Kapitál, legal cover a měkká moc.", description: "Stabilní ekonomika a silné krytí, ale pomalejší underground expanze.", startingPackage: { cleanMoney: 180000, dirtyMoney: 25000, influence: 260, heat: 12 }, advantages: ["Nejvyšší čistý cash start", "Silné legální krytí", "Vyšší diplomacy bias"], disadvantages: ["Slabší dirty pipeline", "Pomalejší bojový náběh"] }
};
